vk_blocks_get_options php unit testを修正
vektor-inc/vk-blocks-pro pull request #1373
Opened 2022-08-16 03:24 UTC by shimotmk

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
#1368

## どういう変更をしたか？

vk_blocks_get_options php unit testを修正しました。
option値を追加した際にデフォルトのオプションが補われるかのテストを追加

このテストがあればレビュー前にユニットテストでエラーになるのでレビューが楽になると思います。

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [x] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [x] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
ユーザーレベルで変更はないので書いていないです
- [x] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

- [x] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

以下、レビュー確認方法同様です。

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーに回す前の確認事項

- [x] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

・php unit testが必要十分か
・もし次にオプション値を追加した際のテストが書けるか(コメントなど)
・他、気になる箇所があったらご指摘お願いします。

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2022-08-17 08:20 UTC, mthaichi commented
@shimotmk 
お疲れさまです。すみません。基本的なことですみませんが、ちょっと教えて下さい！

このテストの目的は、なんでしょうか。#1368 のリファクタリングが関連していると思いますが・・・。

```
vk_blocks_get_options()でデフォルト値とマージしているがそのマージする関数
wp_parse_argsがmarginの中のsmやmdがあるとxlやxsのデフォルト値を埋め合わせてくれない
wp_parse_argsは階層が深いと良い感じにならない、もしくはコアを直しに行く
```

このマージがきちんとされているかというテストでしょうか。
あ、私と相談ってこのあたりのことでしょうか？  いつでもお声がけくださいませ。

2022-08-17 08:34 UTC, shimotmk commented
@mthaichi 
説明不足ですみません。
おっしゃる通りです。

[共通余白のxl、xsのプルリク](#1355)はレビューの際にデフォルト値が埋め合わせされていないことがわかりました
ただ本来はPHP Unit テストで不具合が見つかるべきです

そのための事前準備です。

> あ、私と相談ってこのあたりのことでしょうか？

これについては複数あるのですが内容が固まっていないので相談内容が固まったらお声がけします🙏🙏

2022-08-17 08:45 UTC, shimotmk commented
@doshimaf 
上記のコメントの通りでもあるのですが、このブランチ #1355 でもPHPUnitテストを書くことになると思うので確認お願いできますか。
わからなければお気軽に聞いてください

PHPUnitテストについて参考資料
https://www.notion.so/PHP-Unit-167276274d2d4d84967dd8822fc2c26f

2022-08-17 09:51 UTC, mthaichi approved these changes

2022-08-17 10:12 UTC, mthaichi commented
@shimotmk ありがとうございます。問題ないと思います！

リファクタリングこれからだと思いますが、後世の方々が設定値を追加する時に、テスト側にも書くということが気づけるようにしたいですね。たとえば、VK_Blocks_Options側にもテストも追加することを促すコメントがあるとか。後世の方々が迷わない仕組みがあるといいですね。

テスト自体にも、どうテストを追加するのかコメントがあると親切だと思いました。私なら、他の設定値のコードを見ながら書けそうですが、他の方はどうなのかわかりません。
あんまりコメントだらけになるの抵抗があれば、Notionとか社内ドキュメントに書くのでもいいと思いますが、あんまり参照されていない空気も感じますし、見落としもありますしね。

これから関わる方々に余計な工数を使わせないという視点は大事かなぁと考えています:smile:

2022-08-18 01:17 UTC, shimotmk commented
@mthaichi 
ありがとうございます！

> リファクタリングこれからだと思いますが、後世の方々が設定値を追加する時に、テスト側にも書くということが気づけるようにしたいですね。

知っていると思いますが、VK_Blocks_Optionsにオプション値を追加したらデフォルト値がnullの時に帰ってくる値が変わるのでUnitテストが引っ掛かるのでテストが必要なことは気づくと思います

ただ、
・他のオプション値が保存されている状態から追加したoption値の初期値がmargeされるか

このテストを追加せずに進んでしまう可能性はあります

> テスト自体にも、どうテストを追加するのかコメントがあると親切だと思いました。

ここにどんなテストが必要かコメントは書きましたが、どんなコメントが良さそうでしょうか？？
後世の方々にも出来るだけ気を使ったのですが、
https://github.com/vektor-inc/vk-blocks-pro/blob/c7b05f83b1e33579eee9f377f020c3c8860e46c9/test/phpunit/pro/test-get-options.php#L11-L17

@mthaichi さんならどんなテストを書くのか見てみたいです。

2022-08-21 03:25 UTC, kurudrive requested changes
@shimotmk ありがとうございます。コメントしました。
月曜日に確認よろしくお願いいたします！

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +				),
```suggestion
				'option'  => array(),
```
同じくここも balloon_border_width の初期値テストなので、balloon_border_width 以外の値は不要かなと。
※ もしかして僕が過去に書いたテストの引用とかだったらごめんなさい。

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +			// 吹き出し線の太さ v0.55.0
```suggestion
			// 吹き出し線の太さ v0.55.0 : デフォルト値テスト
```

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +				),
```suggestion
				'option'  => array(),
```

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +			// 余白 単位 margin_unit v1.7.1
```suggestion
			// 余白 単位 margin_unit v1.7.1  : デフォルト値テスト
```

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +			// 余白の共通サイズ設定 margin_size v1.7.1
```suggestion
			// 余白の共通サイズ設定 margin_size v1.7.1 : デフォルト値テスト
```

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +				),
```suggestion
				'option'  => array(),
```

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +			// 分割読み込み load_separate_option v1.21.0
```suggestion
			// 分割読み込み load_separate_option v1.21.0 : デフォルト値テスト
```

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +				),
```suggestion
				'option'  => array(),
```

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +			// ライセンスキー v1.32.0
```suggestion
			// ライセンスキー v1.32.0 : デフォルト値テスト
```

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +				),
```suggestion
				'option'  => array(),
```

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +
```suggestion

			// optionsの配列の中の指定の要素のみテスト
```

2022-08-21 03:25 UTC, kurudrive commented on test/phpunit/pro/test-get-options.php
> +			} else {
```suggestion
			// optionsの全要素をテスト
			} else {
```

2022-08-22 00:35 UTC, shimotmk commented
@kurudrive 
コメントされているテストではテストの意味がないと思います。
optionを軒並み空の配列array()にされていますがそのような状態は無いからです

そして現在このブランチは @mthaichi の[返信待ち](https://github.com/vektor-inc/vk-blocks-pro/pull/1373#issuecomment-1217813906)、 @doshimaf  の`[確認待ち](https://github.com/vektor-inc/vk-blocks-pro/pull/1373#issuecomment-1217698013)`です

2022-08-22 00:54 UTC, kurudrive commented
@shimotmk 

> optionを軒並み空の配列array()にされていますがそのような状態は無いからです

array() に指定するとテスト前に delete_option でオプション値が削除されて、VK Blocks をインストール直後の初期値取得のテストの意図ですが、どうでしょうか（・・？

2022-08-22 01:03 UTC, kurudrive commented
@shimotmk 

ただ、array() だと確かに「その状態はない」になってしまうので、null にするかあるいは、delete_option 処理をする識別要の配列要素を用意して、そこにフラグが立ってたら option 削除する処理の方が適切だったと思います。ごめんなさい (￣人￣)

2022-08-22 01:11 UTC, shimotmk commented
@kurudrive 
プラグインインストール初期状態のテストはここに書いてあります
https://github.com/vektor-inc/vk-blocks-pro/blob/482644386aee04e397d6f90b8286a87cb2b88115/test/phpunit/pro/test-get-options.php#L19-L47

その他のテストはコメントにも書いてありますが
「**他のオプション値が保存されている状態から追加したoption値の初期値がmargeされるか**」のテストです

> delete_option 処理をする識別用の配列要素を用意して、そこにフラグが立ってたら option 削除する処理の方が適切だったと思います。

私の理解不足で何を言っているのか正確に理解できていないのですが、delete_optionは各テストが終わった後に行っているので特定の要素を削除するような処理はこのテストには要らないと思います。
https://github.com/vektor-inc/vk-blocks-pro/blob/482644386aee04e397d6f90b8286a87cb2b88115/test/phpunit/pro/test-get-options.php#L260-L261

2022-08-22 02:04 UTC, mthaichi commented
@shimotmk  要するにテストを「どのように」追加すれば良いか、最初のコメントで誰でも理解できると良いと思います。

たとえば、次にoption値を追加するときですが、
ライセンスキーのところ https://github.com/vektor-inc/vk-blocks-pro/blob/482644386aee04e397d6f90b8286a87cb2b88115/test/phpunit/pro/test-get-options.php#L148-L175
をコピーし、その下に貼り付けて、option_check_targetを新しいoptionのキー、correctを新しいoptionの初期値にすればいいんでしょうか。

ということが、冒頭のコメントを読むだけで分かるといいと思います。
僕は理解するのに（しているかどうかわかりませんが）20-30分かかりました。一つのコメントでそれが短縮できるのであれば、そうしたいなというところですが、いかがですか。

2022-08-22 02:09 UTC, mthaichi commented
@shimotmk あと、テストでひっかかって気づくよりは、テストする前に気付けるとよりいいですよね。
テストでひっかかって「あ、テストがいるのか」と頭が働くとは限らないと思います。
option値を追加するケースは今後増えそうな気もしますので、一定のルールがあって、機械的にできるぐらいだと良いのかなって思いました。

2022-08-22 02:14 UTC, kurudrive commented
@shimotmk 

あ、えっと、ごめんなさい。結論から言うと僕の勘違いが多かったです。
そして、最初に配列内の特定の要素だけ確認すればいいのでは？と僕が安易に提案したのが間違いです。

### array() の指定は確かに意味がない

> 私の理解不足で何を言っているのか正確に理解できていないのですが、delete_optionは各テストが終わった後に行っているので特定の要素を削除するような処理はこのテストには要らないと思います。

は、
https://github.com/vektor-inc/vk-blocks-pro/blob/482644386aee04e397d6f90b8286a87cb2b88115/test/phpunit/pro/test-get-options.php#L236-L237

の事を指していました。ここで delete_option するので初期値のテストができる。

が、さきほどのコメントが勘違いで、僕もここは初期値テストではなく __適当な配列（array）に対してマージされた対象の初期値が正しく取得できるかどうか？__
のテストつもりだったのですが、 array() だと前述のようにこのテスト上で option 値自体が削除された状態でのテストになってしまうのでマージのテストにはならないので array() で実行する事は意味がなかったです。

### 下村さんが書いた array() の中身をなぜ消したか？

結局確認するのが対象要素だけなら、配列の要素が何であれ（array()はだめだけど...）関係ないから削除していいんじゃないかなと思ったためです。
なので、対象のターゲットだけのテストなら、array() は間違いだけれど、適当な要素１行入れておけばOKという思考です。

### マージのテストは配列完全一致テストが正しい

で、今回要素が追加された値で順番に下村さん書いてくれていたのですね。ようやく理解しました。
確認するのが配列内の特定の要素だけなのになんで要素順番に増やしてるのだろう？と思ってました。ごめんなさい。

せっかっくキレイに配列を用意してくれたなら、マージテストは

* もともと入っていた配列の値がマージによって上書き改変される事なくそのまま返ってくるか
* 新規に追加された要素の初期値が正しく返ってくるか

の２つを確認するのが正しいので、配列の中の特定の要素指定ではなく配列全体比較でないと逆に意味がなかったです。

### option_check_target を提案した僕の間違い...

option_check_target なんていう邪道なやりかたを提案した僕の間違いでした...
お手数おかけしてすみません...。

2022-08-22 04:40 UTC, shimotmk commented
@mthaichi 
冒頭のコメントを調整してみましたがいかがでしょうか？
https://github.com/vektor-inc/vk-blocks-pro/blob/98936039a383d555acec85d9063db1c42e38c9a4/test/phpunit/pro/test-get-options.php#L11-L51

> あと、テストでひっかかって気づくよりは、テストする前に気付けるとよりいいですよね。

これはPHPUnitを常時監視するということですか？？
正直なところ実装方法が思い当たらないです🙇‍♂️🙇‍♂️🙇‍♂️

2022-08-22 06:57 UTC, shimotmk commented
全てのオプションを比べると最初の方に追加したテストのcorrectデータが変わるので追加したデータの値のみのテストにしてある

<details>
<summary>**全てのオプション値をチェックするようにしたコード クリックで展開**</summary>
<div>

```PHP
<?php
/**
 * Class GetOptionsTest
 *
 * @package vk-blocks
 */

class GetOptionsTest extends WP_UnitTestCase {

	public function test_vk_blocks_get_options() {
		/**
		 * option値を追加した場合
		 * ・プラグインインストール初期状態
		 * ・他のoption値が保存されている状態から追加したoption値の初期値がmargeされるか
		 * ・全てのオプション値を変更した時
		 * の3つのテストを追加してください
		 *
		 * たとえば、次にoption値を追加するは
		 * 1.ライセンスキーのところのテストをコピー
		 * 2. その下に貼り付ける
		 * 3. optionにvk_blocks_pro_license_keyと保存される値を追加
		 * 4. option_check_targetに追加したoptionのキー、correctを新しいoptionの初期値を設定してください
		 */
		$test_data = array(
			// プラグインインストール初期状態
			array(
				'option'  => null,
				'correct' => array(
					'balloon_border_width' => 1,
					'margin_unit' => 'rem',
					'margin_size' => array(
						'lg' => array(
							'mobile' => null,
							'tablet' => null,
							'pc' => null,
						),
						'md' => array(
							'mobile' => null,
							'tablet' => null,
							'pc' => null,
						),
						'sm' => array(
							'mobile' => null,
							'tablet' => null,
							'pc' => null,
						),
					),
					'load_separate_option' => false,
					'vk_blocks_pro_license_key' => null,
					'display_vk_block_template' => 'display',
					'new_faq_accordion' => 'disable',
				),
			),
			// デフォルトの表示非表示調整 v0.44.13
			// https://github.com/vektor-inc/vk-blocks-pro/commit/b17c2ae4097a5530eb88a7fdcf03885d89ece643#diff-9b75d117946ae115e35175fb160346351a75f98e850679a65de42680bd4611e1
			array(
				'option'  => array(
					'hide_wp_block_template' => true,
					'hide_vk_block_template' => false,
				),
				'correct'  => array(
					'hide_wp_block_template' => true,
					'hide_vk_block_template' => false,
					'display_vk_block_template' => 'display',
				),
			),
			// hide_wp_block_template,hide_vk_block_templateは廃止されたので以降のテストでは追加していない

			// New FAQ アコーディオン機能 v0.46.0
			// https://github.com/vektor-inc/vk-blocks-pro/pull/21
			array(
				'option'  => array(
					'display_vk_block_template' => 'hide',
				),
				'correct'  => array(
					'display_vk_block_template' => 'hide',
					'new_faq_accordion' => 'disable',
				),
			),
			// 吹き出し線の太さ v0.55.0
			// https://github.com/vektor-inc/vk-blocks-pro/commit/e0ede110ada73f0eb65af611382d899469b8d84b
			array(
				'option'  => array(
					'display_vk_block_template' => 'hide',
					'new_faq_accordion' => 'open',
				),
				'correct'  => array(
					'display_vk_block_template' => 'hide',
					'new_faq_accordion' => 'disable',
					'balloon_border_width' => 1,
				),
			),
			// 余白 単位 margin_unit v1.7.1
			// https://github.com/vektor-inc/vk-blocks-pro/pull/584/
			array(
				'option'  => array(
					'display_vk_block_template' => 'hide',
					'new_faq_accordion' => 'open',
					'balloon_border_width' => 2,
				),
				'correct'  => array(
					'display_vk_block_template' => 'hide',
					'new_faq_accordion' => 'open',
					'balloon_border_width' => 2,
					'margin_unit' => 'rem',
				),
			),
			// 余白の共通サイズ設定 margin_size v1.7.1
			// https://github.com/vektor-inc/vk-blocks-pro/pull/584/
			array(
				'option'  => array(
					'display_vk_block_template' => 'hide',
					'new_faq_accordion' => 'open',
					'balloon_border_width' => 2,
				),
				'correct'  => array(
					'display_vk_block_template' => 'hide',
					'new_faq_accordion' => 'open',
					'balloon_border_width' => 2,
					'margin_size' => array(
						'lg' => array(
							'mobile' => null,
							'tablet' => null,
							'pc' => null,
						),
						'md' => array(
							'mobile' => null,
							'tablet' => null,
							'pc' => null,
						),
						'sm' => array(
							'mobile' => null,
							'tablet' => null,
							'pc' => null,
						),
					),
				),
			),
			// 分割読み込み load_separate_option v1.21.0
			// https://github.com/vektor-inc/vk-blocks-pro/commit/b6f3575cb2ebcb4e64ecb8070b81ccd391abc13c
			array(
				'option'  => array(
					'display_vk_block_template' => 'hide',
					'new_faq_accordion' => 'open',
					'balloon_border_width' => 2,
					'margin_unit' => 'px',
					'margin_size' => array(
						'lg' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'md' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'sm' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
					),
				),
				'correct'  => array(
					'display_vk_block_template' => 'hide',
					'new_faq_accordion' => 'open',
					'balloon_border_width' => 2,
					'margin_unit' => 'px',
					'margin_size' => array(
						'lg' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'md' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'sm' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
					),
					'load_separate_option' => false,
				),
			),
			// ライセンスキー v1.32.0
			// https://github.com/vektor-inc/vk-blocks-pro/pull/1166
			array(
				'option_check_target' => 'vk_blocks_pro_license_key',
				'option'  => array(
					'display_vk_block_template' => 'hide',
					'new_faq_accordion' => 'open',
					'balloon_border_width' => 2,
					'margin_unit' => 'px',
					'margin_size' => array(
						'lg' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'md' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'sm' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
					),
					'load_separate_option' => true,
				),
				'correct'  => array(
					'display_vk_block_template' => 'hide',
					'new_faq_accordion' => 'open',
					'balloon_border_width' => 2,
					'margin_unit' => 'px',
					'margin_size' => array(
						'lg' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'md' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'sm' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
					),
					'load_separate_option' => true,
					'vk_blocks_pro_license_key' => null,
				),
			),
			// 全てのオプション値を変更した時
			array(
				'option'  => array(
					'balloon_border_width' => 2,
					'margin_unit' => 'px',
					'margin_size' => array(
						'lg' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'md' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'sm' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
					),
					'load_separate_option' => true,
					'vk_blocks_pro_license_key' => 'test_license_key',
					'display_vk_block_template' => 'display',
					'new_faq_accordion' => 'open',
				),
				'correct' => array(
					'balloon_border_width' => 2,
					'margin_unit' => 'px',
					'margin_size' => array(
						'lg' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'md' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
						'sm' => array(
							'mobile' => 1,
							'tablet' => 2,
							'pc' => 3,
						),
					),
					'load_separate_option' => true,
					'vk_blocks_pro_license_key' => 'test_license_key',
					'display_vk_block_template' => 'display',
					'new_faq_accordion' => 'open',
				),
			),
		);
		print PHP_EOL;
		print '------------------------------------' . PHP_EOL;
		print 'vk_blocks_get_options()' . PHP_EOL;
		print '------------------------------------' . PHP_EOL;
		foreach ( $test_data as $test_value ) {

			if ( empty( $test_value['option'] ) ){
				delete_option( 'vk_blocks_options' );
			} else {
				update_option( 'vk_blocks_options', $test_value['option'] );
			}

			$return  = vk_blocks_get_options();
			$correct = $test_value['correct'];

			// print 'return  :';
			// print PHP_EOL;
			// var_dump( $return );
			// print PHP_EOL;
			// print 'correct  :';
			// print PHP_EOL;
			// var_dump(  [...]

2022-08-23 02:17 UTC, kurudrive approved these changes

2022-08-23 05:43 UTC, doshimaf approved these changes
- Unitテストの動作確認
- 新たにオプション値を追加した際にテストをかけるかどうかの確認

が完了しました。

https://github.com/vektor-inc/vk-blocks-pro/pull/1355

上記の場合に追加すべきテストコード
```
array(
	'option_check_target' => 'margin_size',
	'option'  => array(
		'display_vk_block_template' => 'hide',
		'new_faq_accordion' => 'open',
		'balloon_border_width' => 2,
		'margin_unit' => 'px',
		'margin_size' => array(
			'lg' => array(
				'mobile' => 1,
				'tablet' => 2,
				'pc' => 3,
			),
			'md' => array(
				'mobile' => 1,
				'tablet' => 2,
				'pc' => 3,
			),
			'sm' => array(
				'mobile' => 1,
				'tablet' => 2,
				'pc' => 3,
			),
		),
		'load_separate_option' => true,
	),
	'correct' => array(
		'margin_size' => array(
			'xl' => array(
				'mobile' => null,
				'tablet' => null,
				'pc' => null,
			),
			'lg' => array(
				'mobile' => 1,
				'tablet' => 2,
				'pc' => 3,
			),
			'md' => array(
				'mobile' => 1,
				'tablet' => 2,
				'pc' => 3,
			),
			'sm' => array(
				'mobile' => 1,
				'tablet' => 2,
				'pc' => 3,
			),
			'xs' => array(
				'mobile' => null,
				'tablet' => null,
				'pc' => null,
			),
		),
	),
),
```

2022-08-23 05:45 UTC, merged