【丸山確認中】Update Checker を更新
vektor-inc/vk-blocks-pro pull request #1525
Opened 2022-12-20 04:36 UTC by drill-lancer

## 注意事項
https://github.com/vektor-inc/vk-blocks-pro/pull/1524 の更新分も含みます。

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://github.com/vektor-inc/vk-blocks-pro/issues/1523

## どういう変更をしたか？

バージョン未指定のままだとライブラリ内のクラス名の変更などによって FatalErrorになるため指定

- Plugin Update Checker 5.0 に対応

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [x] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [x] Files changed (変更ファイル)の内容は目視で確認したか？
- [x] readme.txt に変更内容は書いたか？
- [x] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？
⇒アップデートが正常にはしるかどうかで確認できるので保留

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

- プラグイン > インストール済みプラグインで「アップデートを確認」をクリックしてもエラーが起きないことを確認しました。

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーに回す前の確認事項

- [x] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

- プラグイン > インストール済みプラグインで「アップデートを確認」をクリックしてもエラーが起きないことを確認願います。

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2022-12-20 08:00 UTC, mthaichi commented
@drill-lancer Update Checkerを更新したい理由はなんですか？ どこかでお話頂いてたらすみませんが、それも書いておいて頂けますか。

2022-12-20 08:01 UTC, mthaichi commented
> @drill-lancer Update Checkerを更新したい理由はなんですか？ どこかでお話頂いてたらすみませんが、それも書いておいて頂けますか。

あ、これは @kurudrive さんご指名なのか・・・。そのあたり共有できてればいいです。

2022-12-20 08:30 UTC, kurudrive requested changes

2022-12-20 08:30 UTC, kurudrive commented on .wp-env.json
> +	}
@drill-lancer これは関係します？
アップデートチェッカーの指定と直接関係しなければ別のプルリクにしたいです。

2022-12-20 08:33 UTC, kurudrive commented
@mthaichi バージョン未指定のままだとライブラリ内のクラス名の変更によって Fatal Errorになる事があっため、現行のバージョンに指定という流れですー。

2022-12-20 08:35 UTC, drill-lancer commented on .wp-env.json
> +	}
@kurudrive 
すでにしています。
https://github.com/vektor-inc/vk-blocks-pro/pull/1524

2022-12-20 08:56 UTC, kurudrive commented on .wp-env.json
> +	}
@drill-lancer ありがとうございます。
他のプルリクを先にマージしないといけない場合は、
該当のプルリクをマージ後にレビューをする旨の記載よろしくお願いいたします。
でないと、これはなんだろう？  と無駄に考える時間が発生してしまうため。

2022-12-20 12:35 UTC, kurudrive approved these changes

2022-12-20 12:36 UTC, kurudrive commented
@mthaichi ありがとうございます。一応チラ見して問題なければマージいただければと思います。
よろしくお願いいたします。

2022-12-20 12:38 UTC, kurudrive commented
※超急ぎというほどでもないと思うので優先度ラベルははずしました。

2022-12-21 07:00 UTC, mthaichi approved these changes

2022-12-21 07:01 UTC, merged