【WIP】[ダイナミックテキスト表示ブロック]新規作成
vektor-inc/vk-blocks-pro pull request #1527
Opened 2022-12-23 08:45 UTC by doshimaf

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

## どういう変更をしたか？

* このプルリクで変更した事を記載してください
* [ダイナミックテキスト表示ブロック]をPro版ブロックとして作成しました。

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

実装者が確認した手順を箇条書きで記載してください。

*
*
*

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

レビュワーがどういう手順で何を確認して欲しいかを記載してください。

*
*
*

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2023-01-10 03:22 UTC, doshimaf commented
@goutetsuguma 
こちらのブロックのアイコンの作成をお願いできますでしょうか。
よろしくお願いいたします。

2023-02-24 03:30 UTC, kurudrive commented
@doshimaf これ出来ていると思うのでドラフトからオープンに変更で概要諸々記載よろしくお願いいたしますー。

2023-02-24 03:36 UTC, kurudrive commented
@doshimaf あ、ごめんまだだった（・ｗ・； 下書きのままで。

2023-05-11 20:52 UTC, kurudrive requested changes

2023-05-11 20:52 UTC, kurudrive commented on src/blocks/_pro/dynamic-text/index.php
> +	if ( 'ancestor-page' === $options['displayElement'] && ! ( $post->post_parent ) && 'page' !== $post->post_type ) {
@doshimaf ありがとうございます。
たぶんここは === の間違いかと（・ｗ・

```suggestion
	if ( 'ancestor-page' === $options['displayElement'] && ! ( $post->post_parent ) && 'page' === $post->post_type ) {
```

2023-05-13 17:50 UTC, kurudrive approved these changes

2023-05-18 04:47 UTC, drill-lancer commented
@kurudrive @doshimaf 
カスタム投稿タイプ ( Lightning G3 Pro Unit の 404 と ExUnit のカスタム投稿タイプ )で投稿タイプ名を表示しようとしたところ、公開画面では正しい投稿タイプが表示されますが、編集画面では「ブログ」と表示されます。

多分 VKHelper::get_post_type_info() の出力がそうなっているような気がします。

2023-05-19 01:58 UTC, merged