【確認待ち】VK Block Pro のカルーセルのレスポンシブ強化
vektor-inc/vk-blocks-pro pull request #1545
Opened 2023-01-17 07:48 UTC by drill-lancer

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://github.com/vektor-inc/vk-blocks-pro/issues/469

## どういう変更をしたか？

- スライドあたりの表示枚数を Mobile Tablet PC が選択可能に
- もとからあった表示枚数は PC に継承

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

1. develop ブランチで複数枚数表示可能なスライダーを設置
2. このブランチに戻してもリカバリーが発動しないことを確認
3. もともとの設定が PC に継承されているのを確認
4. 適当に設定を変更して公開画面でその通りに反映されているのを確認

## 確認URL

ローカルで確認

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

1. develop ブランチで複数枚数表示可能なスライダーを設置
2. このブランチに戻してもリカバリーが発動しないことを確認
3. もともとの設定が PC に継承されているのを確認
4. 適当に設定を変更して公開画面でその通りに反映されているのを確認
---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2023-01-19 02:10 UTC, doshimaf commented
@drill-lancer ありがとうございます。
このブランチに切替後にリカバリーが発生しないことが確認できました。
また、もとの設定がPCの設定値に反映されていることも確認しました。

「１度の動作で動かす枚数」を手入力で設定・変更したときに、編集画面でコンソールエラーがでます。
また、「１度の動作で動かす枚数」と各画面サイズでの表示枚数の値が異なると、フロントで想定した通りの挙動にならず、バレットも想定した挙動にならないようです。

2023-01-19 04:37 UTC, drill-lancer commented
@doshimaf 
「１度の動作で動かす枚数」の調整とコンソールエラーを調整してみました。
再確認お願いします。

2023-01-19 06:21 UTC, doshimaf commented
@drill-lancer 
ありがとうございます。

編集画面のエラーがなくなりました。
また、すでに追加していたスライダーについては、リカバリーが必要でしたが同じくエラーは出なくなりました。

稀かもしれませんが、下記のようなケースだと意図した動作になりません。

・表示枚数は３枚だけど、一度に動かす枚数は２枚という場合
バレットやナビゲーションで手動で動かす場合は正常に動くが、自動の場合は１枚目のスライドのままになる。

・表示枚数は２枚だけど、一度に動かす枚数は３枚という場合
一度に動く枚数が２枚になる

適切な仕様を把握できていないのですが、特に後者は注意書きか何かがあるといいのかなと思いました。
@kurudrive

2023-01-19 06:32 UTC, drill-lancer commented
@doshimaf @doshimaf 
一度に動かす枚数 slidesPerGroup は一度に表示する枚数 slidesPerView と同じにしないと何らかの不具合が発生しそうな感じです。

2023-01-19 06:41 UTC, doshimaf commented
@drill-lancer 
なるほど！
ちなみに、一度に動かす枚数の設定項目を、slidesPerView か 1 の2択にするのはどうでしょうか？
その方が迷いも減りますし、不具合が発生する選択肢をなくすこともできるのではないかと思いました。

2023-01-19 06:42 UTC, drill-lancer commented
@kurudrive @doshimaf 
一度に動かす枚数 slidesPerGroup は一度に表示する枚数 slidesPerView の約数でも問題なさそうです。

2023-01-22 00:19 UTC, kurudrive commented
@drill-lancer 実装ありがとうございます。

@doshimaf 確認ありがとうございます。大嶋さんの改善案は理解しました。

> slidesPerView % slidesPerGroup = 0 なら問題ないということです。

とりあえず現状も仕様では slidesPerView % slidesPerGroup = 0 じゃないケースは問題になるという事は把握していると思うので、RICKさんはどういう仕様が良いと思いますか？

2023-01-22 00:22 UTC, drill-lancer commented
@kurudrive 
slidesPerView にはスライドの枚数の約数を入れるように
slidesPerGroup にも slidesPerView の約数を入れるように
そういった注釈をいれつつ数値は自由に変更可能という感じで考えています。

2023-01-22 00:45 UTC, kurudrive commented
@drill-lancer @doshimaf 
ふーむ、多分使う人は「約数に」って言われると考えないと意味がわからない or 考えても意味が理解できない人が多く、
結局フォーラムに「不具合だ」とか言ってくる人が発生すると思いました。
なので、注釈だけという対応は避けたいです。

なので、

■ A案（大嶋案）
一度に動かすスライドの数 ← 画面サイズ毎の指定は不要
[ スライドビューと同じ | 一つずつ ]

■ B案
一度に動かすスライドの数について、

* slidesPerView % slidesPerGroup = 0 でない場合、
  slidesPerView % slidesPerGroup = 0 になるまで slidesPerGroup -1 をループして自動調整する
* 自動調整した場合にその旨アラートメッセージ・説明を表示

かなと思いますが、B案は
* 実装面倒そう
* 自動調整した場合に説明を表示してもユーザーがいまいち理解できない人が発生しそう

という事を踏まえると、A案の方が無難ではないかなと思いますがどうでしょう？

※月曜日以降に返信すればよきですよ

2023-01-22 00:47 UTC, drill-lancer commented
@kurudrive 
では A 案で行こうと思います。

2023-01-22 00:56 UTC, kurudrive commented
@drill-lancer これ一応月曜に他の人の意見も聞いてみましょう。

■問題点
例えば
一度に表示する数を3、
一度にスライドさせる数を2に指定すると、最初のスライドはいいけど、次のスライドは歯抜けになる。
まぁ歯抜けでも人によってはありというかもしれないけど、

■どうする？
大嶋さんが気付いてくれたA案が妥当かなと思いつつ、
https://github.com/vektor-inc/vk-blocks-pro/pull/1545#issuecomment-1399367786
いやいやいや、例えば6枚表示の２枚ずつスライドとか必要っしょ！
とか、僕としてはそれはないかなと思ってますが「こういうケースだと有効だし！」みたいな事もあるかもしれないので、僕は大嶋さんのA案推しですが、他の意見ありますか？

特に
@goutetsuguma @sysbird @ChiakiKouno @kaorock72 さんどうでしょう？
Cc: @mthaichi @shimotmk

2023-01-22 09:31 UTC, goutetsuguma commented
@kurudrive @doshimaf @drill-lancer 

たしかに１度の動作で動かす枚数が選べてしまうとややこしいし変な設定をして不具合だと言われそうですね、、汗
気づいていただいてありがとうございます！
大嶋さんのA案がシンプルでわかりやすいと思います！

 >[ スライドビューと同じ | 一つずつ ]
 ↑「スライドビューと同じ」も選べるの、めっちゃ嬉しいです。（わたしがみた他者のスライダーブロックは1枚だけしかできなかったので）

2023-01-22 11:23 UTC, drill-lancer commented
@kurudrive @goutetsuguma 
たしかに同一スライドに1、２、３、５、（７、11）枚表示する場合は約数が２つしかないのでそれでも良いと思います。
（７枚以上は個人的にも微妙なのでカッコ書き）

同一スライドに４枚表示する場合２枚ずつ動かすケース、
同一スライドに６枚表示する場合２枚ずつ、３枚ずつ動かすケースに需要があるかないか
多分このあたりが議論の焦点になりそうです。

2023-01-22 11:40 UTC, kurudrive commented
> 同一スライドに４枚表示する場合２枚ずつ動かすケース、
> 同一スライドに６枚表示する場合２枚ずつ、３枚ずつ動かすケース

そうそう。このケースを個人的に見たことがないので、
僕が見たことないだけで「実はこんなケースで有効だ 」というのを見たことある人がいたらあとから他のユーザーにリクエストされて困るのも嫌なので教えてほしいなと。
なければ大嶋さん案で良いと思います。

2023-01-23 00:12 UTC, kaorock72 commented
いろいろ調整ありがとうございます！わたしもA案でまずはいいのでは？と思いました。よろしくお願いします

2023-01-23 02:00 UTC, sysbird commented
A案がよいと思います
B案は細かい設定でありがたい場合もありますが、私には難しいです
調整ありがとうございます！

2023-01-23 03:00 UTC, drill-lancer commented
@kurudrive 
A 案が多かったので A 案で実装しました。

2023-01-23 06:03 UTC, doshimaf approved these changes
@drill-lancer 
調整ありがとうございます！

2023-01-23 19:27 UTC, kurudrive commented
@drill-lancer 変更ありがとうございました。

@goutetsuguma @sysbird @ChiakiKouno @kaorock72 @doshimaf 
Cc: @mthaichi @shimotmk

はい...ここで再び問題が発生しました。

* 登録スライド : 4枚（ A B C D ）
* 表示枚数 : 3枚（ A B C | D ）
* 一度に動くスライド : 表示枚数と同じ

の場合に、初期表示はよくても次の表示どうする問題が発生しました。

この場合考えられるのは

a案. 残りの１枚（D）は表示するが足りない２枚分を余白にする
b案. 残りの１枚を表示しつつ足りない２枚はABで埋める（DAB） 
  → 次の移動は１枚（D）分だけにして その次はまた ABC から始まる
  → その旨注意文の追加は必要
c案. 登録枚数が表示枚数で割り切れない場合は自動的に１枚ずつスライドにする
  → その旨注意文の追加は必要

かなと思います。
まぁ全くの余白が発生する a 案はないかなと。

現状は b の仕様になっているっぽいです。
ただ、やっぱり足りない分のスライドのところは違和感があります。

となると c案の 方が安定するかなと思いつつ、
でも登録が 10 枚だったら少なくとも 3セットは普通に表示されるわけで、
そっちの方がいいという考え方もありっちゃあり...。

個人的には微妙に c案かなと思いますがみなさんどう思います？

2023-01-24 01:30 UTC, drill-lancer commented
@kurudrive @goutetsuguma @sysbird @ChiakiKouno @kaorock72 @doshimaf
Cc: @mthaichi @shimotmk

追加プランD：

１～６までの数字において登録スライドの枚数の約数のみ選択肢に表示
例：登録スライド数が６枚なら 1, 2, 3, 6 が選択肢に表示
例：登録スライド数が７枚なら 1 が選択肢に表示
例：登録スライド数が12枚なら 1, 2, 3, 6 が選択肢に表示

2023-01-24 01:45 UTC, goutetsuguma commented
Rickさん追加のD案ありがとうございます！そんなことができるのですね。
追加プランD案　が個人的には良いかなと思いました。（スライドの枚数の約数のみ選択肢に表示されると注意書きも追加）

b案→足りないスライド分のところで若干違和感がある
C案→こちらでも良いけどより対応できるD案がでてきたので

2023-01-24 01:47 UTC, kurudrive commented
@drill-lancer あー、なるほど...
確かにそれはいいですね。

と、思いきや...

後からスライドアイテムを削除された場合カオスにならない（・・？

2023-01-24 01:49 UTC, drill-lancer commented
@kurudrive 
あとからスライドが追加・削除された瞬間にその値を検査して
表示枚数が登録スライド数の約数でなければ強制的に１に戻せば問題ないかと

2023-01-24 02:03 UTC, kurudrive commented
1. スライドアイテム合計4登録
2. 表示枚数を mobile 1 / tablet 2 / PC 4 / "表示枚数分スライド" に設定
3. スライドアイテムを後から一つ削除して合計3になる

> 強制的に１に戻せば問題ないかと

これは移動スライドを１に戻すという意味かな？
それとも
mobile 1 / tablet 1 / PC 1 / "表示枚数分スライド"

にするって事？

どのみちスライドを減らされたら、表示枚数の再計算処理は必要そうですよねぇ...
初期実装はまだしもメンテナンス混乱しそうだなぁ...

表示枚数が、存在アイテムの約数じゃなかったら -1 ずつして約数に自動変換する処理は必要そうね...。

2023-01-24 02:05 UTC, drill-lancer commented
1. スライドアイテム合計4登録
2. 表示枚数を mobile 1 / tablet 2 / PC 4 / "表示枚数分スライド" に設定
3. スライドアイテムを後から一つ削除して合計3になる

この場合は表示枚数を 1 にして、さらに移動スライドも１になるという寸法です。

2023-01-24 02:13 UTC, kurudrive commented
@drill-lancer なるほどー。

たぶん ４枚表示がいきなり１になるのはまずいと思うのよね。

1. スライドアイテム合計4登録
2. 表示枚数を mobile 1 / tablet 2 / PC 4/ "表示枚数分スライド" に設定
3. スライドアイテムを後から一つ削除して合計3になる
4. 表示枚数を mobile 1 / tablet 1 / PC 3/ "表示枚数分スライド"

1. スライドアイテム合計9登録
2. 表示枚数を mobile 1 / tablet 3 / PC 3 / "表示枚数分スライド" に設定
3. スライドアイテムを後から一つ削除して合計8になる
4. → 削除された時点で再計算して mobile 1 / tablet 2 / PC 2

みたいな感じが理想。
つまり、

* PCの表示枚数が全アイテム数より大きい場合はアイテム数に自動変換
* 各サイズの表示枚数がアイテム数の約数じゃない場合 → 約数になるまで -1 

って仕様かな。

2023-01-24 02:19 UTC, drill-lancer commented
@kurudrive 
「これらの設定はすべてのスライダーを設定し終えてから設定して」
「この注釈を無視したら全てが１になる」
という旨の注釈を加えるつもりで考えています。

自動調整についてはそこまでフォローする必要があるかは僕個人としては疑問です。

2023-01-24 02:30 UTC, kurudrive commented
> 自動調整についてはそこまでフォローする必要があるかは僕個人としては疑問です。

たし🦀

そして追加で気づいたのが、枚数の変動について、
たとえば、スライドアイテムが3枚あって、それぞれ A B C と違うレイアウトだった場合、
C を削除して かわりに B と同じレイアウトのスライドアイテムを配置したい場合、
C を削除した時点でリセット処理が走ると、合計枚数はかわってないのにまた表示枚数指定をしないといけないって事になるので、それは面倒だと思うんですよね。

じゃあ、saveのタイミングでリセットする？って事になったりするけど、
もうそんな面倒な事しないで、現状仕様で「表示枚数はアイテム全体の約数になるように指定してください。」って注釈でいいような気がしてきました...（＝ｗ＝；

2023-01-24 02:31 UTC, sysbird commented
a案. 残りの１枚（D）は表示するが足りない２枚分を余白にする
はナシになってますが
私はこれが自然に感じます

自動的におぎなったり、選択肢が増えたり注釈はわかりずらいです(私にとって)
ユーザーが枚数を調整するでは使いずらいでしょうかね？

2023-01-24 02:38 UTC, goutetsuguma commented
>現状仕様（b案）で「表示枚数はアイテム全体の約数になるように指定してください。」って注釈でいいような気がしてきました...（＝ｗ＝；

わたしも現状使用のb案で良い気がしました。（仕様が複雑になるとメンテが大変）
足りない時に若干違和感あるけどイレギュラーな設定しているので仕方ないかと思われます。


> ユーザーが枚数を調整するでは使いずらいでしょうかね？

とりさんの意見もわかります！でも初心者の方の場合は、良きにはからって埋めてほしいのかな？と思ったりしました。
a案だと気づかずに空白のままにしてしまうユーザーは一定数いそうだなと。。

2023-01-24 02:44 UTC, sysbird commented
たしかに〜
b案は、よく見れば違和感ですが表示がヘンになることはないですね

2023-01-24 02:44 UTC, kurudrive commented
@sysbird 確認ありがとうございます。

僕も自然だとは思うのですが、多分、足りない分って swiper の仕様上空のスライドアイテムを自動的に挿入するとかしないと無理じゃないかな？
@drill-lancer 

現状 b案 の仕様に加えて、

表示数入力欄の上に

「表示枚数はスライドアイテムの数を割り切れる数を指定してください。割り切れない数字の場合はスライドの挙動が不自然になります。」

の注釈追加、

約数じゃない場合はリアルタイムで表示数設定欄の下に
「スライドアイテムの数を割り切れる数を指定してください。」
という警告を表示するようにする。
ただし、実際の保存値はこの時自動補正しない
※自動補正すると最終的なスライドアイテム数では問題ない数字だったのに再度手動で調整しないといけなくなる事があるため

みたいな感じが落とし所かな？

2023-01-24 02:47 UTC, drill-lancer commented
@kurudrive
了解しました。

@goutetsuguma @ChiakiKouno @kaorock72 @doshimaf
https://github.com/vektor-inc/vk-blocks-pro/pull/1545#issuecomment-1401326451
上記で問題ないですね？

2023-01-24 02:48 UTC, kurudrive commented
これが現状仕様に一番近いし、無駄にプログラムが複雑化しないからメンテナンス面でも良さそうな気がします。

2023-01-24 04:05 UTC, drill-lancer commented
@kurudrive @doshimaf @goutetsuguma @goutetsuguma @ChiakiKouno 
https://github.com/vektor-inc/vk-blocks-pro/pull/1545#issuecomment-1401326451
上記に仕様で実装してみました。（alert のクラスはまだあたってない）

2023-01-24 04:59 UTC, goutetsuguma commented
@kurudrive @drill-lancer 
表示数入力欄のメッセージと約数じゃない場合のメッセージ、確認できました！

ちょっとだけ質問です、約数じゃない数字を入れていて「One by One」を選択した時に「Specify a number that divides the number of slide items.」のメッセージがでます。「One by One」を選択したときはメッセージが非表示の方がわかりやすいのかなと思いましたが、調整が難しいかもしれないのでこのままでもOKです🙇‍♀️

2023-01-24 05:04 UTC, drill-lancer commented
@goutetsuguma 
> 「One by One」を選択した時に「Specify a number that divides the number of slide items.」のメッセージがでます。
まず、一度に表示するスライドの枚数が全体の約数になっているか否かが重要です。
そして、一度にスライドする枚数が一度に表示するスライドの枚数の約数になっている必要があります。

「One by One」は一度にスライドする枚数の話なので、選択してもメッセージが表示されるのは正常です。

2023-01-24 05:27 UTC, goutetsuguma commented
リックさんありがとうございます🙇‍♀️理解しました！

（2人目確認待ちにしましたが、わたしはコードレビューができませんのでカウントして良いのかな、、？？）

どなたか、確認をよろしくお願いいたします

2023-01-24 05:33 UTC, drill-lancer commented
「One by One」の場合一度に表示するスライドの枚数がスライドの総枚数の約数でなくても問題なさそうだったので警告を修正しました。

2023-01-24 06:26 UTC, kurudrive requested changes
@drill-lancer 「互換設定」だけだと、何の互換設定の事かわからない（将来的にタイミングをみて削除できる場合はしたい）ので、どういう意図の互換設定なのかわかるコメントが欲しいです。

2023-01-24 06:26 UTC, kurudrive commented on src/blocks/slider/edit.js
> +		if (
```suggestion
		@since 1.50
		1.49 までは slidesPerGroup は 数字での保存のみだったため、
		1 の場合は one-by-one に、 1 以外の数字指定だった場合は slides-per-view になるように
		if (
```

2023-01-24 06:26 UTC, kurudrive commented on src/blocks/slider/edit.js
> +		// slidesPerViewMobile 互換設定
@drill-lancer 
これは「互換」設定？
1.50 以降は必ず数字で入ってくるけど、1.49 からのユーザーだと undefined が来るって事？

2023-01-24 06:28 UTC, drill-lancer commented on src/blocks/slider/edit.js
> +		// slidesPerViewMobile 互換設定
@kurudrive 
そうなるので入れています。

2023-01-24 06:29 UTC, kurudrive commented
@drill-lancer 多分今は直接触ってるのでコードの意味を把握してると思いますが、
他の人や年月が経ってからみた時に変更背景が想定できるコメントをよろしくお願いいたします (￣人￣)

2023-01-24 06:48 UTC, drill-lancer commented
@kurudrive 
コメントを修正してみました。

2023-01-24 08:53 UTC, kurudrive commented
@drill-lancer ありがとうございます。

あとはアラートのCSSを調整よろしくお願いいたします。
以前はサイドパネルにもエディタのCSSが効いちゃってた気がするのですが、今は効かなくなった感じなのかな。

数値によって表示するメッセージは alert 無しの素の赤字でも良いですよ。

対応しやすい方で...。

2023-01-25 00:46 UTC, drill-lancer commented
@kurudrive 
alert の css が効くように調整しました。

2023-01-25 18:27 UTC, kurudrive approved these changes

2023-01-25 18:35 UTC, kurudrive commented
@drill-lancer ありがとうございます！
複数枚表示の実用性・応用度がずっと上がったと思います！
Good Job!! 👍👍👍👍👍

2023-01-25 18:35 UTC, merged