【確認待ち】余白設定にカスタム値を追加
vektor-inc/vk-blocks-pro pull request #1598
Opened 2023-03-08 01:48 UTC by drill-lancer

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

https://github.com/vektor-inc/vk-blocks-pro/issues/1595

## どういう変更をしたか？

- 共通余白設定にカスタム値を追加

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

- npm run phpunit
- 実際にスペーサーブロックを設置して CSS が反映されるか確認

## 確認URL

ローカル環境

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

- npm run phpunit
- 実際にスペーサーブロックを設置して CSS が反映されるか確認

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2023-03-08 12:32 UTC, kurudrive requested changes

2023-03-08 12:32 UTC, kurudrive commented on src/blocks/spacer/index.php
> +	} elseif ( ! empty( $options['margin_size'][ $spacer_size ][ $device ] ) ) { // 各サイズのデバイス毎のサイズ.
@drill-lancer これだと 0 が指定できなくない？

2023-03-09 00:44 UTC, drill-lancer commented on src/blocks/spacer/index.php
> +	} elseif ( ! empty( $options['margin_size'][ $spacer_size ][ $device ] ) ) { // 各サイズのデバイス毎のサイズ.
@kurudrive 
isset に変更しました。

2023-03-10 08:48 UTC, mthaichi commented
@drill-lancer @kurudrive XSS対策が必要かなと思います。いまのままですと、例えば以下のような設定をこっそり忍ばせることも可能です。
使えるCSS関数名を絞って、セミコロンなどは入力できないようにするなどの対策を取れますか。

![image](https://user-images.githubusercontent.com/1535140/224266354-34ce302e-357b-4419-8172-9485a85c502f.png)

2023-03-10 09:07 UTC, mthaichi commented
@kurudrive @drill-lancer  
入力できるのは、「カスタムCSS」ではなく、余白の「値」ですよね。数値以外にもCSS関数が使えますよ。ってとこですよね。（間違ってたらすみません） そこがちょっとピンと来ませんでした。 

で、「余白の値」を入力する欄であるのに、書いたものがそのままCSS出力されるのは、良くないんじゃないかってことです。関数が入力できてもいいのですが、余白値として相応しい内容を出力するようにバリデーションをかけるべきだということを申し上げております。

2023-03-10 12:03 UTC, kurudrive commented
@mthaichi @drill-lancer 
うーむ、どうですかねぇ...。出力でエスケープしてあるのと、CSSとなると相当バリエーションがある＆新しく追加になるルールもあるので、CSSの出力系で特別にルール作ってエスケープしてるの見たことないので個人的には良いのではないかなという気もしますが...

まぁでも確かに使うのは長さに関係する部分だけなので ; が出てきたら ; から後ろはすべて削除しちゃうとか、url() が出てきたら中身は削除しちゃうとか禁止処理の追加なら現実的に対応かなという肌感ですがどうですかね？

余談ですがヌートバーさん大活躍ですな。という事を入力している間に近藤選手ホームランおめでとうございます。

2023-03-10 14:00 UTC, mthaichi commented
@kurudrive  
「CSSの関数名は制限する。」「セミコロンから後ろは削除する。」の2点は最低限必要かなと思います。

WordPressの界隈のことはよくわかりませんが、そもそもCSSを入力させるというのが、一般的にはアンチパターンなので、HTMLやCSSを入力させる設計は良くないと教えられます。

ただ、WordPressの場合は性質上やむを得ないのは理解できます。設定画面はサイト管理者しかアクセスできないので、ある程度は許容できます。（管理者が目を話しているすきに第三者が・・・ということもありますが）

とはいえ「HTMLやCSSコードを打たせるのは最終手段」という意識を持って頂き、やむなく入力フォームの内容をHTMLやCSSにインジェクトする場合は、十分注意を払うということは、多くの人が利用するプロダクトを出している会社の責任ではないかと思います。

コードがオープンになっているので、見る人が見れば、あんまりガバガバなのは良い印象を持たれないかと。
あと、WAFによっては、ひっかかって使えないということもあるかもです。（WordPressを使う多くの人がOFFにしている気もしますが）

2023-03-10 14:27 UTC, kurudrive commented
@mthaichi なるほど...。あくまで前向きな議論としてなのですが、
気になったのが、WordPressのエスケープ関数 esc_attr() は通して無害化してから出力しているので、
独自実装のエスケープ処理作って追加する事は複雑化や誤動作につながるので避けたほうが良いと聞いた記憶があってどうかなと...

でも確かに WAF にひっかかる可能性とか上がりそうですね...

2023-03-13 09:31 UTC, mthaichi commented
@kurudrive  esc_attr はHTMLエンティティへの置き換え処理が主なので、それ以外のセキュリティ対策はしてくれないはずです。もちろんエスケープ処理は esc_attr にまかせればいいと思いますし、そこは現状でもできているんじゃないですかね。
それ以外の無害化処理を入れる必要はあるかと。

Reactでそういう処理が難しければ、とりあえず セミコロン(;) 以降を削除するだけでも良いと思います。
できるのであれば、つかえるCSS関数名を制限できたらなおよいと思います。

ちなみに
https://wpdocs.osdn.jp/%E9%96%A2%E6%95%B0%E3%83%AA%E3%83%95%E3%82%A1%E3%83%AC%E3%83%B3%E3%82%B9/register_setting

にあるように register_settingの第３引数にサニタイズ関数を渡すようになっているので、ここで無害化しろということなのだと思います。が、VK BlocksはSetting APIを使わず、値をupdateしていると思いますし（たぶん）、画面もReact化されているので、React側で無害化すればよいのかなーという感じです。

2023-03-13 17:15 UTC, kurudrive commented
@drill-lancer ↓のルールでいけそう？

- [ ] 入力内容に ; が含まれていたら ; 以降をすべて削除して保存する

できれば...

- [ ]  ( が含まれていた場合、( の前の文字列が以下の文字列以外の場合は () 内の文字列を削除して保存する

*  var
* clamp
* min
* max
* calc

2023-03-15 00:07 UTC, drill-lancer commented
@kurudrive 
想定しているものの中で正規表現 `/[a-z0-9\/%\+\-\*\(\), ]+/`で弾かれそうなものってありますか？

2023-03-15 01:31 UTC, kurudrive commented
@drill-lancer 

> 想定しているものの中で正規表現 /[a-z0-9\/%\+\-\*\(\), ]+/で弾かれそうなものってありますか？

ワカリマセン

> 害をなすコードの入力は可能ですか？

入力自体はできても保存時に弾けば良いのではないかなと。

2023-03-15 02:54 UTC, mthaichi commented
> @kurudrive @mthaichi 想定しているものの中で正規表現 `/[a-z0-9\/%\+\-\*\(\), ]+/`で弾かれそうなものってありますか？ あと、害をなすコードの入力は可能ですか？

お手数をおかけします。
上記の意味合いがわからなかったのですが、
以下のようなコードで、セミコロンから後ろを削除し、関数名を抽出できるかと。

PHP
```
$css = 'color: rgb(255, 0, 0);
background: linear-gradient(to bottom, #ffffff, #000000);
transform: translateX(100px);';

// セミコロンから後ろを削除
$css = mb_substr( $css , 0 , mb_strpos($css, ";") );

// 関数名を抽出 $matches[1] に
preg_match('/([a-zA-Z][\w-]*)\s*\(/', $css, $matches);
var_dump($css);
var_dump($matches[1]);
```

JS
```
const css = 'color: rgb(255, 0, 0); background: linear-gradient(to bottom, #ffffff, #000000); transform: translateX(100px);';
  
// セミコロンから後ろを削除
const trimmedCss = css.substr(0, css.indexOf(';'));

// 関数名を抽出 matches[1] に
const regex = /([a-zA-Z][\w-]*)\s*\(/;
const matches = regex.exec(trimmedCss);
const functionName = matches[1];

console.log(trimmedCss);
console.log(functionName);
```

2023-03-15 03:07 UTC, mthaichi commented
@drill-lancer  あ、こんなんで良い気もします。JS例ですが。
しっかり検証はしていないですが、こんな雰囲気で行ける気が。

```
const css = 'clamp(255, 0, 0); background: linear-gradient(to bottom, #ffffff, #000000); transform: translateX(100px);';
  
// セミコロンから後ろを削除
const trimmedCss = css.substr(0, css.indexOf(';'));

// 関数名を抽出 matches[1] に
const regex = /(var|clamp|min|max|calc)\s*\(/;
const matches = regex.exec(trimmedCss);

// nullじゃなければマッチしている
if ( null !== matches) {
  console.log(matches[1]);
}
```

2023-03-15 04:47 UTC, drill-lancer commented
@kurudrive @mthaichi 
>しっかり検証はしていないですが、こんな雰囲気で行ける気が。
`const css = 'clamp(255, 0, 0); background: linear-gradient(to bottom, #ffffff, #000000); transform: translateX(100px);';
  
// セミコロンから後ろを削除
const trimmedCss = css.substr(0, css.indexOf(';'));

// 関数名を抽出 matches[1] に
const regex = /(var|clamp|min|max|calc)\s*\(/;
const matches = regex.exec(trimmedCss);

// nullじゃなければマッチしている
if ( null !== matches) {
  console.log(matches[1]);
}`

`calc(var(--variable-width) + 20px)`みたいな場合も存在しうるのでこれが通れば良いのですが

入力された値が `/[a-z0-9\/%\+\-\*\(\), ]+/` にマッチしなければ弾くというのを考えています。

2023-03-16 00:36 UTC, drill-lancer commented
@mthaichi @kurudrive 
```
const css = 'clamp( aaa( 255 ), 0, 0); background: linear-gradient(to bottom, #ffffff, #000000); transform: translateX(100px);';
  
// セミコロンから後ろを削除
const trimmedCss = css.substr(0, css.indexOf(';'));

// 関数名とカッコを抽出して比較
const regex01 = /(var\s*\(|clamp\s*\(|min\s*\(|max\s*\(|calc\s*\()/g;
const regex02 = /\w+\s*\(/g;
const matches01 = trimmedCss.match(regex01);
const matches02 = trimmedCss.match(regex02);

console.log(matches01);
console.log(matches02);
console.log( JSON.stringify(matches01) === JSON.stringify(matches02) )`

```

この最終行が true なら trimmedCss を保存、そうでなければ何もしないという感じで考えています。
いかがでしょうか？

2023-03-16 09:35 UTC, mthaichi commented
> この最終行が true なら trimmedCss を保存、そうでなければ何もしないという感じで考えています。 （上記コードは false を返すので何もしない） いかがでしょうか？

@drill-lancer いいと思います。ありがとうございます。さすがです。
正規表現の部分を、関数名の部分を var|clamp|min|max|calc  みたいにできるとメンテナンス性がいいなと思い、アレンジしてみました。
ご参考までに。（使っても使わなくてもいいです）


```
const css = 'clamp( var( 255 ), 0, 0); background: linear-gradient(to bottom, #ffffff, #000000); transform: translateX(100px);';
  
// セミコロンから後ろを削除
const trimmedCss = css.substr(0, css.indexOf(';'));

// 関数名とカッコを抽出して比較
const regex = /\b(?:(var|clamp|min|max|calc)\s*\()|\w+\s*\(/g;
const matches = [];
let match;
while ((match = regex.exec(trimmedCss)) !== null) {
  if (match[1]) {
    matches.push(match[1]);
  } else {
    matches.push(null);
  }
}

console.log(matches);
console.log(matches.every(x => x !== null));

```

2023-03-17 05:19 UTC, drill-lancer commented
@mthaichi @kurudrive 
サニタイズ処理（PHP）の追加とその関数のテストを書きました。

2023-03-20 07:14 UTC, kurudrive commented
@drill-lancer これ RICK さんの環境だと正常に保存できます（・ｗ・？

https://user-images.githubusercontent.com/3272660/226271083-b74ea390-33a5-4cc9-9298-7df611ef8c2f.mov

2023-03-20 07:27 UTC, drill-lancer commented
@kurudrive 
カスタム値に表示されているハイフン２つが棒線１つに変換されているのが原因です。
`var( --wp--custom--spacing--xx--small )` なら普通に通ります。

2023-03-20 08:11 UTC, kurudrive approved these changes

2023-03-20 08:14 UTC, merged

2023-03-20 09:13 UTC, kurudrive commented
@drill-lancer ありがとうございましたーん