Add/dynamic text/ancestor page display option
vektor-inc/vk-blocks-pro pull request #1684
Opened 2023-05-25 06:03 UTC by doshimaf

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://github.com/vektor-inc/vk-blocks-pro/issues/1677

## どういう変更をしたか？

* このプルリクで変更した事を記載してください

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

実装者が確認した手順を箇条書きで記載してください。

*
*
*

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

レビュワーがどういう手順で何を確認して欲しいかを記載してください。

*
*
*

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2023-05-25 15:44 UTC, kurudrive requested changes

2023-05-25 15:44 UTC, kurudrive commented on src/blocks/_pro/dynamic-text/block.json
> +		"displayOption": {
@doshimaf ありがとうございます。
これは先祖階層の固定ページにのみ関連するオプション値なので、今後表示要素が増えた時に displayOption だと「何のdisplayOption?」となってしまうので、ancestorPageDisplayOption などの方がいいかなと思います。

2023-05-26 00:31 UTC, doshimaf commented on src/blocks/_pro/dynamic-text/block.json
> +		"displayOption": {
ありがとうございます。
属性名を変更しました。
https://github.com/vektor-inc/vk-blocks-pro/pull/1684/commits/ffae024f50710fa1b6947b757b3b23f1424980c2

2023-05-26 03:21 UTC, doshimaf commented
@kurudrive
現在、displayElementの値に関わらず常に表示されるオプションのチェックボックスについて、先祖階層の固定ページが選択された場合にのみ表示するような仕様の方が良いでしょうか？
先祖階層の固定ページが選択されていない場合はオプションのチェックボックスが表示されないほうが良いかもしれないと思い確認しました。

2023-05-27 15:09 UTC, kurudrive commented
@doshimaf 

> 先祖階層の固定ページが選択された場合にのみ表示するような仕様の方が良いでしょうか？

はい、それでよろしくお願いいたします。

2023-05-28 23:56 UTC, doshimaf commented
@kurudrive 
オプションの表示条件を変更しました。
また確認をお願いいたします。

2023-05-29 02:45 UTC, kurudrive approved these changes

2023-05-29 02:45 UTC, kurudrive approved these changes

2023-05-29 02:51 UTC, kurudrive commented
@doshimaf ありがとうございます。

オプション名がなど改めて見たらちょっと違和感があった（僕の指示ですが...）ので少しだけ調整しました。

2023-05-29 09:54 UTC, mthaichi approved these changes
@doshimaf  問題ないとおもいますので、Approveしますが、これを確認している中で、#1691 に遭遇したので、確認頂けると嬉しいです。

2023-05-29 09:57 UTC, mthaichi commented
@doshimaf  翻訳のコンフリクトだけ修正いただければと🙏
（明日の夕方でよければ、私やってもいいのですが）

2023-05-30 00:08 UTC, doshimaf commented
@mthaichi 
確認ありがとうございます。
https://github.com/vektor-inc/vk-blocks-pro/issues/1691
こちらについても後ほど確認して対応します。
コンフリクトを解消したのでマージします。

2023-05-30 00:29 UTC, merged