add: display license setting hook
vektor-inc/vk-blocks-pro pull request #1720
Opened 2023-06-08 06:31 UTC by drill-lancer

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

https://github.com/vektor-inc/vk-blocks-pro/issues/1719

## どういう変更をしたか？

- ライセンスキーの設定の表示・非表示の切り替えができるフィルターフックを追加

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

- [ ] 書けそうなテストは書いたか？
=> フックを追加しただけで仕様には影響しないので省略

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

`$display_license_setting = apply_filters( 'vk_blocks_dipsplay_license_setting', true );`
上記において

1. VK Blocks の設定画面に移動しライセンスキーを設定して保存
2. true を false に書き換えて再読み込み
3. ライセンスキーのフォームがごっそり表示されないのを確認
4. 設定を保存後再読み込み
5. false を true に戻して再読み込み
6. ライセンスキーのフォームが表示され中身が入っているのを確認

## 確認URL

ローカル環境

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

`$display_license_setting = apply_filters( 'vk_blocks_dipsplay_license_setting', true );`
上記において

1. VK Blocks の設定画面に移動しライセンスキーを設定して保存
2. true を false に書き換えて再読み込み
3. ライセンスキーのフォームがごっそり表示されないのを確認
4. 設定を保存後再読み込み
5. false を true に戻して再読み込み
6. ライセンスキーのフォームが表示され中身が入っているのを確認

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2023-06-08 19:56 UTC, kurudrive commented
@drill-lancer これhookの場所なのですが、ライセンスが有効な時だけ隠せる場所にできませんか？

と、いうのは、制作者が非表示にカスタマイズするだけして音信不通になると、
ライセンスが切れた後でサイトオーナーから「ライセンスキーの入力場所がない」とかいう問い合わせが来たりすると面倒なので...

2023-06-11 18:02 UTC, kurudrive commented
> => フックを追加しただけで仕様には影響しないので省略

いや...フックの追加だけでなく関数なども増えていて、この変更でライセンス判定に問題がないかは全く保証されていないので必要です。原則テストの追加は必須でお願いします。

■ vk_blocks_license_check() のテストを追加してください。
■ vk_blocks_is_license_setting() のテストを追加してください。
■ もう少しコメントを書いてください。例えば vk_blocks_license_check の場合、ライセンスのチェックとは何の事なのか？ライセンスが有効化をチェックするものなのか、ライセンスチェックが必要なのかをチェックするのか、どういう値を返すのか

「APIを叩いて UpdateChecker の返り値がごにょごにょなのでテストが書きにくい」と思うかもしれませんが、
APIを叩かなくても返り値を引数で渡すなど、必要に応じてテストしやすい関数・メソッドに改変してください。

2023-06-21 04:19 UTC, drill-lancer commented
@kurudrive 
修正しましたので確認お願いします。

2023-06-23 15:11 UTC, kurudrive requested changes

2023-06-23 15:11 UTC, kurudrive commented on readme.txt
> +[ Other ][ Heading style ] Cope with dark background color
```suggestion
```

2023-06-23 15:12 UTC, kurudrive approved these changes

2023-06-23 15:15 UTC, kurudrive commented
どなたか二人目確認よろしくお願いいたします。

レビュー時の留意事項 : 
* ライセンスキーの内容を変更した場合は更新を再取得しないと期待する動作になりません
* プラグインなどにフィルターを書いて実行する場合は雑ですが下記のような感じで動作すると思います。

```
add_filter( 'vk_blocks_license_key_display_setting', function(){
	return false;
},11 );
```

2023-06-26 12:45 UTC, merged