【確認待ち】New Badgeブロック新規追加
vektor-inc/vk-blocks-pro pull request #1792
Opened 2023-08-21 08:31 UTC by mthaichi

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
#1695 

## どういう変更をしたか？
- New Badgeブロックの新規追加並びにPHPUnitテスト追加

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

実装者が確認した手順を箇条書きで記載してください。

* 新規記事を作成、そこに「New Badge」ブロックを追加
* DAYS COUNTED AS NEW POST にNewを表示する日数を指定
* 記事の日付を上記で指定した日数より古い日にちに設定した時に、薄く表示されるようになることを確認。
* フロント側では、古い日にちを設定した時に表示がされないことを確認。
* さまざまなスタイルを指定して、フロント側に反映されるか確認。
* ブロックテーマにして、お知らせ表示などに本ブロックを設置し、適切に動作するか確認

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

レビュワーがどういう手順で何を確認して欲しいかを記載してください。

* 新規記事を作成、そこに「New Badge」ブロックを追加
* DAYS COUNTED AS NEW POST にNewを表示する日数を指定
* 記事の日付を上記で指定した日数より古い日にちに設定した時に、薄く表示されるようになることを確認。
* フロント側では、古い日にちを設定した時に表示がされないことを確認。
* さまざまなスタイルを指定して、フロント側に反映されるか確認。
* ブロックテーマにして、お知らせ表示などに本ブロックを設置し、適切に動作するか確認

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2023-08-22 05:18 UTC, kurudrive approved these changes

2023-08-22 05:19 UTC, kurudrive commented
@mthaichi ありがとうございます！確認しました！

2023-08-22 05:36 UTC, sysbird commented
@mthaichi 
確認中ですー
角丸がフロントに反映されないです
枠線を付けると角丸になるので、仕様でしょうかね？

2023-08-22 05:41 UTC, mthaichi commented
> @mthaichi 確認中ですー 角丸がフロントに反映されないです 枠線を付けると角丸になるので、仕様でしょうかね？

@sysbird すみませんー。再現ができないので、再現方法を具体的に示して頂けますか？
背景色有で、枠線がない時の角丸という意味でしょうか。

2023-08-22 05:46 UTC, sysbird commented
> 背景色有で、枠線がない時の角丸という意味でしょうか。

@mthaichi 
はい、そうです〜
背景赤、テキスト黄色、幅フィット、角丸20px です

【編集画面】
![new-edit](https://github.com/vektor-inc/vk-blocks-pro/assets/4631838/d960ea7f-22ca-420d-bfd2-895733ecb75e)
【フロント】
![e-front](https://github.com/vektor-inc/vk-blocks-pro/assets/4631838/79967b1f-4120-49fe-a6af-0d8c50ba2b9c)

2023-08-22 05:51 UTC, mthaichi commented
> > 背景色有で、枠線がない時の角丸という意味でしょうか。 
> @mthaichi はい、そうです〜 背景赤、テキスト黄色、幅フィット、角丸20px です

@sysbird 自分の環境では、再現できないでもうちょっと教えてください。
「幅フィット」というのは、具体的にどこの設定ですか？ 
WordPressのバージョンと確認しているブラウザも教えてもらえますか？
あと、最新の本ブランチをプルしてくださってますか？   以前見て頂いた時とブランチ名も変わっています。
何度もすみませんー。

2023-08-22 05:55 UTC, mthaichi commented
@sysbird 「幅フィット」理解しました。すみません。

2023-08-22 06:01 UTC, sysbird commented
はい、ブランチ名は気づきました

ブラウザはFireFox とChrome で見てますが変わりないようです
WP 6.3 で確認していますので、6.2 でも見てみますね

2023-08-22 06:16 UTC, sysbird commented
@mthaichi 
WP 6.3 と 6.2 で同じ現象でした
ブラウザのキャッシュは都度消しています

2023-08-22 06:26 UTC, sysbird commented
@mthaichi 
たびたびすみませんー
再現方法わかりました

枠線が空白だ角丸が効かないみたいです
枠線に 0 と入力すると枠線なしの角丸背景で表示されます(← やりたいのこれ)
デフォルトが空白なので気になるところです

ご検討おねがいできますでしょうか

2023-08-22 06:56 UTC, mthaichi commented
@sysbird ありがとうございます。
枠線の幅が未指定かつ角丸を指定した時に再現できました。枠線に数値が入っていることになかなか気が付けず、失礼しました。修正しましたので、ご確認ください。

2023-08-22 07:11 UTC, mthaichi commented
セルフチェックで不具合を見つけてしまったので、マージしないでください。すみません。

2023-08-22 07:57 UTC, mthaichi commented
@sysbird すみません。問題を修正しましたので、もう一回プルしてご確認ください🙏

2023-08-22 09:50 UTC, kurudrive commented
@mthaichi 調整ありがとうございます。

> 経過日数の設定ですが、今日も含めた日数がいいと思いますか？

24時間で処理するのが良いのではないかと思いますがどうでしょう？

2023-08-22 09:52 UTC, kurudrive commented
@mthaichi あー、いや、処理が面倒かな、どうしよう...。考えます。

2023-08-22 11:37 UTC, mthaichi commented
> @mthaichi あー、いや、処理が面倒かな、どうしよう...。考えます。

@kurudrive「1」と指定したら24時間で消えるという意味ですよね。どっちでも大丈夫ですよ。明快ですよね。
私は日単位の方がしっくりくるので、日単位にしたのですが、「1」と入れた時に、今日だけなのか昨日も入るのか分かりづらいですね。

2023-08-22 12:28 UTC, kurudrive commented on src/blocks/_pro/post-new-badge/index.php
> +use VektorInc\VK_Helpers\VkHelpers;
@mthaichi これって使ってなくないです？

2023-08-22 12:29 UTC, kurudrive commented on src/blocks/_pro/post-new-badge/index.php
> +use VektorInc\VK_Helpers\VkHelpers;
@mthaichi これって使ってなくないです？

2023-08-22 12:37 UTC, sysbird commented
私も日単位がよいかなーと思います

そこで「1日」で設定すると昨日までの分となると、今日だけの設定ができないので
→ 昨日は含めないようにしておくと、足りない分は設定でプラスしていけばよいのではないかと
いかがでしょうか？

2023-08-22 12:39 UTC, kurudrive commented
@mthaichi @sysbird そうね、普通に１日 は当日だけの扱いでいいと思います！

2023-08-22 16:28 UTC, mthaichi commented
@kurudrive @sysbird ありがとうございます。日付判定はその用に変更しました。改めてご確認ください。🙏

2023-08-23 00:30 UTC, kurudrive requested changes

2023-08-23 00:36 UTC, kurudrive commented on src/blocks/_pro/post-new-badge/index.php
> +		$extra_attributes['style'] = implode( ' ', $styles );
@mthaichi ここ以外は特に気になるところはありませんでしたー！

2023-08-23 01:26 UTC, kurudrive approved these changes

2023-08-23 03:02 UTC, mthaichi commented
@sysbird チェック中に修正してしまってすみません。出力されるインラインCSSにスペースが中途半端に入るのが気に入らなくて、直してしまいました。


> @mthaichi 経過日数の確認しました 対応ありがとうございます！
> 
> 枠線なしで角丸をしたとき、テキスト色の枠線が表示されてしまう気がします お手数かけますが、見てもらえますでしょうか〜

@sysbird お忙しい中、ご確認ありがとうございます！
コアのボタンブロックと同じ挙動だと思うのですが、枠線の太さを0に設定すれば、枠線は表示されません。
枠線に線の太さを指定して、線の色を指定しない場合に、テキストの色がそのまま枠線の色になると思います。
線の色を指定すれば、そちらが優先されるはずです。
認識が間違ってたら、すみませんー。

2023-08-23 03:04 UTC, mthaichi commented
@sysbird あ、枠線の太さを指定市内にも関わらず線が出るということですね。すみません。確認します。

2023-08-23 03:14 UTC, shimotmk commented
@mthaichi さん

テキスト色をクリアした時の編集画面と公開画面の色が違います。

https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/f41b800c-e24f-4c3f-9f0c-91b6d336e7db

index.phpで無駄な処理も多くあると思うので一度冷静に方法を見直した方が良いと思いますよ。
コアに逆らうと後々地獄を見るので
https://github.com/vektor-inc/vk-blocks-pro/pull/1792/files#diff-4751c4ce2fcc010d5bd796c26abf465452d57014c1a902793dfc8c7fddd33a76R34-R105
https://github.com/vektor-inc/vk-blocks-pro/issues/1695#issuecomment-1641405314

デフォルトのattributesを上書きしたいならブロックバリエーションでisDefaultをtrueにすれば通常のブロックと同じような動きになります
https://ja.wordpress.org/team/handbook/block-editor/reference-guides/block-api/block-variations/

2023-08-23 04:10 UTC, mthaichi commented
> @sysbird チェック中に修正してしまってすみません。出力されるインラインCSSにスペースが中途半端に入るのが気に入らなくて、直してしまいました。
> 
> > @mthaichi 経過日数の確認しました 対応ありがとうございます！
> > 枠線なしで角丸をしたとき、テキスト色の枠線が表示されてしまう気がします お手数かけますが、見てもらえますでしょうか〜
> 
> @sysbird お忙しい中、ご確認ありがとうございます！ コアのボタンブロックと同じ挙動だと思うのですが、枠線の太さを0に設定すれば、枠線は表示されません。 枠線に線の太さを指定して、線の色を指定しない場合に、テキストの色がそのまま枠線の色になると思います。 線の色を指定すれば、そちらが優先されるはずです。 認識が間違ってたら、すみませんー。

@sysbird ありがとうございます。こちらは修正しましたので、ご確認ください。

2023-08-23 04:20 UTC, mthaichi commented
> @mthaichi さん
> 
> テキスト色をクリアした時の編集画面と公開画面の色が違います。
> 
@shimotmk ありがとうございます。
本ブロックは、初期値として、テキストスタイルに赤を指定しています。
その場合、クリアを押すと色が取れるのですが、そのまま保存して再読み込みすると、初期値の赤に戻ります。
variationを定義してもこの動作は変わらないと思いますが、より具体的な解決方法をコードで示してもらえると嬉しいです。
初期値にテキストスタイルを指定しているようなブロックは見当たらないので、そもそも初期値にテキストスタイルは指定しないほうが良いということでしょうか。

index.php も特にコアを逆らっているつもりはありません。
こちらも改善事項を具体的に示して頂けると助かります。

2023-08-23 04:36 UTC, shimotmk commented
@mthaichi 
まさかそんな答えが返ってくるとは想定してませんでした。
こんな感じの方がシンプルに出来ると思います
https://github.com/vektor-inc/vk-blocks-pro/pull/1794

2023-08-23 05:37 UTC, mthaichi commented
> @mthaichi まさかそんな答えが返ってくるとは想定してませんでした。 こんな感じの方がシンプルに出来ると思います #1794

@shimotmk 申し訳無い限りです🙏
私は、そのコードはあと一週間しても出てきません。私の勉強不足です。
マージさせていただいて、余分なコードを削除して、もう一度確認していただきます。
すごく勉強になりました。ありがとうございます！

2023-08-23 05:40 UTC, mthaichi commented
@sysbird というわけで、いったん調整中にしますので、レビューもうちょっと待ってください。
今日も時間を割いて、何度も確認していただいたのに申し訳ありません。心よりお詫び申し上げます。🙇‍♂

2023-08-23 05:42 UTC, shimotmk commented
@mthaichi 
いえいえ、知らないことは誰にでもあります。
ただ、アドバイスを全く試していただけなかったように思えたので、もう少し試していただきたかったです。

2023-08-23 05:50 UTC, mthaichi commented
> @mthaichi いえいえ、知らないことは誰にでもあります。 ただ、アドバイスを全く試していただけなかったように思えたので、もう少し試していただきたかったです。

@shimotmk もちろん試しました。バリエーション自体は動作したのですが、指定の仕方が悪かったのか、上記の不具合をうまく改善することはできませんでした。
このブランチは優先度が高く、私の取れる時間が限られており、これ以上調査して改修していると相当時間がかかってしまうので、お力添え頂きました。感謝申し上げます。

2023-08-23 06:49 UTC, mthaichi commented
@kurudrive @sysbird @shimotmk 
みなさん、ありがとうございます。調整の上、動作確認をいたしましたので、改めて確認頂ければと思います。

2023-08-24 01:38 UTC, sysbird approved these changes

2023-08-24 01:41 UTC, sysbird commented
@mthaichi 
確認しました、動作問題ないと思います
対応ありがとうございました！

@kurudrive 
修正がはいりましたので、お手数ですが確認してマージしていただけますでしょうか〜

2023-08-24 02:40 UTC, shimotmk commented
> @kurudrive @sysbird @shimotmk みなさん、ありがとうございます。調整の上、動作確認をいたしましたので、改めて確認頂ければと思います。

@mthaichi 
すみません
![pose_syazai_sliding_dogeza_man](https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/1a49698f-6d0e-47db-911e-3bcd87ea0fb7)

`__experimentalSkipSerialization`を削除したのでedit.jsのborderProps関連も要らないです


あと横並びにしたときに幅を設定するとeditorとfrontで異なります

| editor | front |
| ---- | ---- |
| ![editor](https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/18e676bd-d12e-401a-9759-08f6ecb39b27) |  ![front](https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/0e6fd041-276d-4ea7-ba44-e6baae0bd19d) |

塗りつぶしにしたパターンはこの様な形です。

テーマはTwenty Twenty-Three,X-T9でも同じでした。

```HTML
<!-- wp:query {"queryId":0,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
<div class="wp-block-query"><!-- wp:post-template -->
<!-- wp:group {"style":{"spacing":{"margin":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group" style="margin-top:var(--wp--preset--spacing--30);margin-bottom:var(--wp--preset--spacing--30)"><!-- wp:post-date /-->

<!-- wp:post-title /-->

<!-- wp:vk-blocks/post-new-badge {"content":"New!","backgroundColor":"luminous-vivid-amber","textColor":"black","style":{"layout":{"selfStretch":"fill","flexSize":null}}} /--></div>
<!-- /wp:group -->
<!-- /wp:post-template -->

<!-- wp:query-pagination -->
<!-- wp:query-pagination-previous /-->

<!-- wp:query-pagination-numbers /-->

<!-- wp:query-pagination-next /-->
<!-- /wp:query-pagination -->

<!-- wp:query-no-results -->
<!-- wp:paragraph {"placeholder":"クエリーが結果を返さない場合に表示するテキスト、またはブロックを追加してください。"} -->
<p></p>
<!-- /wp:paragraph -->
<!-- /wp:query-no-results --></div>
<!-- /wp:query -->
```

ブロックエディターはcssのdisplay:block;に由来しているのでブロック単体ではwidthは設定せずに自然な形にした方が良いと思います。

もしインサーターから挿入したこのブロックの幅をコンテンツに合わせたいならgruopブロック(横並び)のバリエーションとして登録した方が余計なdivも不要になりエディタとフロントで差異が少なくなると思います。


後から何度もすみません.申し訳ないです🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

2023-08-24 07:27 UTC, mthaichi commented
@shimotmk いえいえ、ありがとうございます。
修正したものを  add/new-badge-block-refactor ブランチにプッシュしてみたのですが、いかがでしょうか。

- borderProps削除
- 余計なdiv削除
- width: max-content 削除
- テキストアラインメント復活（max-contentを廃止するなら必要だと判断したので）

@kurudrive add/new-badge-block-refactor ブランチ 確認して頂いて、使い勝手など問題ないか確認いただけますか。@shimotmkさんの意図も満たしていると思いますし（多分）、挙動もコアのpost系のブロックに準拠しつつ、それほど以前と使い勝手も変わりがないのかと思います。

2023-08-30 05:38 UTC, kurudrive commented
@mthaichi 確認しました。特に問題ないと思いますー。

2023-09-04 05:16 UTC, shimotmk commented
@mthaichi 
ありがとうございます

6.3から入った脚注がうまく動作しない気がします。
```HTML
<!-- wp:paragraph -->
<p>aaaaaaaaaaa<sup data-fn="8db0db9d-f333-4969-8c88-551c388ff978" class="fn"><a href="#8db0db9d-f333-4969-8c88-551c388ff978" id="8db0db9d-f333-4969-8c88-551c388ff978-link">1</a></sup>aaaaaaaaaaa</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>bbbbbbbbbbbbbbbbbb<sup data-fn="b5e73419-163e-4a97-9b6c-e54a32f0a02f" class="fn"><a href="#b5e73419-163e-4a97-9b6c-e54a32f0a02f" id="b5e73419-163e-4a97-9b6c-e54a32f0a02f-link">2</a></sup>bbbbbbbbbbb</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>cccccccccccc<sup data-fn="d844b05e-b771-4c29-9325-f0ccb1e375c9" class="fn"><a href="#d844b05e-b771-4c29-9325-f0ccb1e375c9" id="d844b05e-b771-4c29-9325-f0ccb1e375c9-link">3</a></sup>ccc</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>ddddddddddddddd<sup data-fn="63a8a68d-bb44-4c03-815c-7dc664f48d85" class="fn"><a href="#63a8a68d-bb44-4c03-815c-7dc664f48d85" id="63a8a68d-bb44-4c03-815c-7dc664f48d85-link">4</a></sup>dddddddd</p>
<!-- /wp:paragraph -->

<!-- wp:vk-blocks/post-new-badge {"content":"\u003ccode\u003eNew!\u003c/code\u003e eeeeeeeeeeeeeeeeeeeeeeee\u003csup data-fn=\u0022bc918742-fe07-473d-8310-7ac3cf4dfe1d\u0022 class=\u0022fn\u0022\u003e\u003ca href=\u0022#bc918742-fe07-473d-8310-7ac3cf4dfe1d\u0022 id=\u0022bc918742-fe07-473d-8310-7ac3cf4dfe1d-link\u0022\u003e*\u003c/a\u003e\u003c/sup\u003eeeeeeeeeeeeeeeeeeee","textAlign":"center","style":{"color":{"text":"#ff0000"}}} /-->

<!-- wp:paragraph -->
<p>dddddddddddddddddddd<sup data-fn="2ad922be-61ee-48ad-ab14-d262c7142aaf" class="fn"><a href="#2ad922be-61ee-48ad-ab14-d262c7142aaf" id="2ad922be-61ee-48ad-ab14-d262c7142aaf-link">5</a></sup>ddd</p>
<!-- /wp:paragraph -->

<!-- wp:footnotes /-->
```

editor-css/_editor_before.scssのセレクターが少し違うかなと。

2023-09-04 07:56 UTC, mthaichi commented
> editor-css/_editor_before.scssのセレクターが少し違うかなと。

@shimotmk すみません。ここのおっしゃっている意味が分からないので教えてもらえますか？
ともあれ、脚注を本ブロックで使うことはあまり考えにくいので無効にしてもいいのかなと思いますが、いかがでしょう。

2023-09-07 05:20 UTC, shimotmk commented
@mthaichi 
現時点でのコードでは`.editor-block-list-item-vk-blocks-post-new-badge`というセレクターはブロックエディタ上に存在しないので不要なコードです。

> ともあれ、脚注を本ブロックで使うことはあまり考えにくいので無効にしてもいいのかなと思いますが、いかがでしょう。

これについては私は判断できないです。
脚注を使いたいと思う人もいるかも知れません
ただ、カスタム書式や他のプラグインが追加した書式を使いたいケースはあると思います。

2023-09-07 08:33 UTC, mthaichi commented
@shimotmk ありがとうございます！
そのセレクタは、インサーターパネルのアイコンに出てくる「Pro」の文字を出すためのものですが、バリエーションを使うと
.editor-block-list-item-vk-blocks-post-new-badge/new-badge と `/(variation name)`  を後ろにつけるようで、そこを見落としていました。修正しましたので、「Pro」マークがつくようになっていると思います。

脚注については、その後、コアの「投稿者」ブロックの署名欄もうまく動作していないように見えるので、サーバーサイドレンダリングしているブロックでは問題があるのかもしれません。（勘違いだったらすみません）
ただ、上述のように本ブロックの性質上「脚注」については不要だと私は考えています。
@kurudrive さん、いかがでしょうか。

2023-09-07 17:48 UTC, kurudrive commented
@mthaichi ループで表示するので脚注をつける事自体が用法として間違いなので「脚注」は不要です。

> （追記）脚注を無効にするように改修してプッシュしてみました。

おや？無効になります？普通にツールバーから選択できません？

2023-09-07 22:30 UTC, mthaichi commented
> @mthaichi ループで表示するので脚注をつける事自体が用法として間違いなので「脚注」は不要です。
> 
> > （追記）脚注を無効にするように改修してプッシュしてみました。
> 
> おや？無効になります？普通にツールバーから選択できません？

@kurudrive  ご確認ありがとうございます。修正前のコードに戻すと脚注が選択できて、最新のコードにすると選択できないことを改めて確認しましたので、プルして頂ければ、選択できないと思いますが、いかがでしょう。edit.php に ALLOW_FORMAT の定義があればOKです。

2023-09-08 01:46 UTC, kurudrive commented
@mthaichi あー、ブランチが違いました。無効になってました。良いと思います（・ｗ・

2023-09-11 05:34 UTC, mthaichi commented
@shimotmk 
上記のようなことで、脚注は今回対応しないということで、ご理解頂き、その上で @shimotmk さんに改めてレビュー頂けると、私は安心です。その後、２人目チェックを経てマージできればと思います。お手数ですが、どうぞよろしくお願い致します。

2023-09-12 07:18 UTC, mthaichi commented
@shimotmk @kurudrive みなさん、ありがとうございます。
しもむらさん、コードを示してくれて、ありがとうございます。
私の環境ではうまく動かなかったのですが、修正頂いた点を一つひとつ確認しながら調整してみます。
その上で改めて相談させて頂きますね。

2023-09-14 03:51 UTC, mthaichi commented
@shimotmk さんのコードを参考に修正したところ、脚注も動くので問題ないと思います。

私の知識不足なもので、このケースはサーバーサイドで出力するしかないと思っていました。その場合に脚注がうまく動かないのを回避するのは難しいことなのかなと思いました。それは「投稿者」ブロックの署名欄に脚注を入れるとうまく動かないことから判断しました。

VKボタンブロックでも書式は制限していますし、ブロックの性質上脚注をいれるといったニーズが低いことから、そこにこだわって時間をかけるより、書式を制限して、リリースしてもいいのかなと思いました。

でも、しもむらさんがさくっとそれを回避するコードを示して頂いたので、脚注をいれることは問題ありません。
勉強になりました。

カスタム書式や他プラグインが追加する書式については、これも単に僕の引き出しが少ないだけのことで、allowformatに書式を指定すしか方法がないのかなと思っていました。特定の書式を除外する方法も示して頂いたのでこれも勉強になりました。

もうちょっと確認をした後でこちらに反映して、改めて確認をお願いしたいと思います。
取り急ぎご報告と御礼まで。

2023-09-20 00:53 UTC, mthaichi commented
@shimotmk 下村さんのコードを参考に修正してみましたので、一度見て頂けますか？  何度も申し訳ありません！
脚注は残してあります。

2023-09-21 04:33 UTC, shimotmk commented
> @shimotmk 下村さんのコードを参考に修正してみましたので、一度見て頂けますか？ 何度も申し訳ありません！ 脚注は残してあります。

@mthaichi 
That works for me.

2023-09-21 07:11 UTC, mthaichi commented
@shimotmk ありがとうございます。
ではあと、もうお一方にチェックしていただいて、問題なければマージという形で良いでしょうか。
@osmdik さんか @sysbird  さんあたりに２人目チェック頂けると嬉しいです。

2023-09-25 00:29 UTC, osmdik approved these changes
レビュワー確認方法で問題なく動作することを確認しました。

2023-09-25 00:29 UTC, merged