【機能追加】[パンくずリスト] パンくずリストの区切り線の設定追加
vektor-inc/vk-blocks-pro pull request #1938
Opened 2024-03-26 05:07 UTC by mtdkei

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

#1935 

## どういう変更をしたか？

パンくずリストの区切り線を / 以外のデザインを選べるようにしました。
翻訳はまだです。potから変更してみてるのですが翻訳できてないのでここには入れてません。

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [x] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

実装者が確認した手順を箇条書きで記載してください。

* 設定 > Vk Blocks > Breadcrumb Separator Setting でデザインを選択
* パンくずリストを使っているページを開く
* パンくずリストのデザインが変更を確認

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

レビュワーがどういう手順で何を確認して欲しいかを記載してください。

* 設定 > Vk Blocks > Breadcrumb Separator Setting でデザインを選択します。
* パンくずリストを使っているページを開きます。
* パンくずリストのデザインが変更されていたらOKです。

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2024-03-26 08:51 UTC, kurudrive requested changes

2024-03-26 08:51 UTC, kurudrive commented on src/admin/breadcrumb-separator.js
今後他の設定も追加する可能性があるので -separator はなくてもいいかなと...（・ｗ・

2024-03-26 08:51 UTC, kurudrive commented on src/admin/breadcrumb-separator.js
> +						},
@mtdkei これ普通にテキスト入力の方が自由度が高くてよくない（・ｗ・？

2024-03-26 23:40 UTC, mtdkei commented on src/admin/breadcrumb-separator.js
> +						},
@kurudrive 

ご確認ありがとうございます。
選択肢があった方が簡単に変えられるイメージがつきやすいかもしれないと思って選択肢にしてみました。(非デザイナーだけどちょっとカスタマイズしたい人向けですかね。)
とはいえおっしゃる通り、こだわりがある時には入力できたほうが自由度が高くていい気がするので、以下のような仕様を考えてみました。

1. セレクトボックスの一番下or設定なしの下に「区切り線を入力する」のような欄を追加
2. 「区切り線を入力する」を選んだ後にセレクトボックスの下にテキスト欄が出現or非活性化されていたテキスト欄が活性化される
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/b4f1ce47-5a08-4fb7-abae-7d86c8397f04)

あとは「区切り線を入力する」を選んだにも関わらず何の入力がない場合は「Nothing(/)」が選ばれるようにすればなんとかなるかなあと思いました。

穴があるかもしれないのですがこんな感じでどうでしょうか？

2024-03-27 00:04 UTC, kurudrive commented on src/admin/breadcrumb-separator.js
> +						},
@mtdkei ありがとうございます！
なるほど、いいですね！

と...返信しようとして画面を改めて見たのですが、
やはり、「テキストを入力する」を選択したのに入力がない場合にどうなるんだろう...と思ってしまった時点で、
その場合はこうする という条件分岐処理が発生し、それに対してテストを書いたり他の人の可読性・メンテナンスの問題が発生するので、可能な限りシンプルにしたいです。

現状の VK Blocks Pro も何か改修が入ると他の人が書いたコードを解読する所から始まるので、高度な実装をすると後から死ぬのです...。

大丈夫、高度な実装が必要な場面は今後いくらでもでてきます（＝ｗ＝；

と、いう事でテキスト入力欄だけでよろしくお願いいたします。

ただし、ユーザー的に選択肢があった方がイメージがつきやすいというのはごもっともなので、普通に

例) `/` ,` >` , `≫`

みたいな感じで良いのではないかと（・ｗ・

2024-03-27 00:14 UTC, mtdkei commented on src/admin/breadcrumb-separator.js
> +						},
@kurudrive
ありがとうございます！ 
そうですね、「テキストを入力する」を選択したのに入力がない場合の部分があやふやだった例で示してみます。

2024-03-27 01:31 UTC, mtdkei commented
@kurudrive 
セレクトボックスからテキスト欄に変更しました。よろしくお願いいたします。

2024-03-27 02:02 UTC, kurudrive requested changes
@mtdkei  (´；ω；｀)

Warning: Undefined array key "vk_blocks_pro_breadcrumb_separator" in /var/www/html/wp-content/plugins/vk-blocks-pro/inc/vk-blocks/build/blocks/_pro/breadcrumb/index.php on line 60

2024-03-27 02:40 UTC, mtdkei commented
@kurudrive 
ご確認ありがとうございます。こちらで修正できたかと思いますがどうでしょうか？

2024-03-27 11:40 UTC, kurudrive approved these changes

2024-03-27 11:41 UTC, merged

2024-03-27 23:59 UTC, mtdkei commented
@kurudrive 
色々とご調整いただきありがとうございました。
プレビュー表示はできたらいいなあと思っていたのですがよくわかってませんでした。とてもわかりやすいです。

2024-03-28 01:26 UTC, kurudrive commented
@mtdkei いやぁ、「ちょこっとだからUI修正指示画像書くより組んだ方が早いかなー」と思って手を出したら思ったより（いつも通り）苦戦してしまいました...。

実装ありがとうございました！！