【確認待ち】アコーディオンブロックに「装飾なし」スタイルを追加
vektor-inc/vk-blocks-pro pull request #1941
Opened 2024-03-28 02:43 UTC by mtdkei

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

#1864 

## どういう変更をしたか？

アコーディオンブロックのスタイルに「装飾なし」を追加しました。

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

実装者が確認した手順を箇条書きで記載してください。

*
*
*

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

レビュワーがどういう手順で何を確認して欲しいかを記載してください。

*
*
*

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2024-03-28 07:20 UTC, mthaichi commented
@mtdkei @kurudrive  ベースがmasterになってますが、develop じゃなくてよいですか？
私の方で変えようと思いましたが、意図があるといけないなと思いまして確認します。

<img width="1164" alt="image" src="https://github.com/vektor-inc/vk-blocks-pro/assets/1535140/4f4f3d51-0535-4d90-ac05-fca03cbac609">

もし意図がなければ、vk-blocks-proでは、baseをmasterではなくdevelop が通常運用ですので、そのようにして頂ければと。もしmasterから変更したのであれば、developの内容をマージする必要があると思います。

意図があってmasterにしているなら失礼しました。
ご不明点があれば、遠慮なく聞いて下さい！

2024-03-28 07:21 UTC, kurudrive commented
VK Blocks だけはまだ develop 運用が正しいですー。

2024-03-28 07:23 UTC, mtdkei commented
@mthaichi @kurudrive 
ご指摘ありがとうございます！やり直します。

2024-03-29 01:06 UTC, goutetsuguma commented
@mtdkei ありがとうございます！確認しました。

おそらく装飾なしを選択する人は、アコーディオンタイトル（.vk_accordion-trigger）部分とアコーディオンコンテンツ（.vk_accordion-target）部分にグループブロックを入れて自由に余白や背景色を調整したいと思いますので、余白も0にすると使いやすくなると思いました。余白を0にすると↓以下の画像のように背景に色を自由につけれます

![-サイトタイトル-br-サイトタイトル](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/87e30f08-3495-4141-ab90-27231c91a3bd)

【編集画面】
編集画面では、ダッシュ線のボーダーをつけると見やすくなるかもしれません。
例えば「背景なし」スタイルにすると編集画面ではダッシュ線のボーダーがつきますので、そのようなイメージです。

2024-03-31 23:47 UTC, mtdkei commented
@goutetsuguma 
ご意見ありがとうございます！
おっしゃる通り、アコーディオンに装飾をする可能性が考えられるため、以下の変更を行ってみました。
- 管理画面でアコーディオンの枠線を表示するための変更
- 「装飾無し」は余白が入らないように変更
お手数ですが再度ご確認いただけたら幸いです。

2024-04-01 03:29 UTC, goutetsuguma requested changes
確認いたしました！2点ありますのでご確認お願いいたします。

2024-04-01 03:29 UTC, goutetsuguma commented on src/blocks/_pro/accordion/style.scss
> +		&:not(.is-style-vk_accordion-plain){
not指定があるので、全てのスタイルの余白が0になっているようです。
not指定を外して`.is-style-vk_accordion-plain &`とするのが正しいかもしれません。

2024-04-01 03:29 UTC, goutetsuguma commented on src/blocks/_pro/accordion/style.scss
> +		&:not(.is-style-vk_accordion-plain){
not指定があるので、全てのスタイルの余白が0になっているようです。
not指定を外して`.is-style-vk_accordion-plain &`とするのが正しいかもしれません。

2024-04-01 04:33 UTC, mtdkei commented
@goutetsuguma 
早速のご確認をありがとうございました。
指定の仕方に誤りがあったため、SCSSを修正しました。

2024-04-01 04:49 UTC, goutetsuguma approved these changes
修正ありがとうございます！問題なさそうです

2024-04-02 03:35 UTC, sysbird commented
確認しました、
余白を調整していただいてカスタマイズしやすいですね、ありがとうございます！
マージします

2024-04-02 03:50 UTC, merged