padding_left_and_rightの指定がある場合Paddingを追加
vektor-inc/vk-blocks-pro pull request #1983
Opened 2024-04-18 01:25 UTC by mtdkei

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

#1981 

## どういう変更をしたか？

padding_left_and_rightの指定がある場合Paddingを追加しました。
(コアのpaddingの値ではleftとかrightとか別々につけられなくて、ひとまずpadding全体に数値がついています。)

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [x] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

実装者が確認した手順を箇条書きで記載してください。

*
*
*

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

レビュワーがどういう手順で何を確認して欲しいかを記載してください。

*
*
*

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2024-04-19 19:16 UTC, kurudrive requested changes

2024-04-19 19:16 UTC, kurudrive commented on src/blocks/slider-item/edit.js
> +				case '0px':
@mtdkei ここはただの識別用数値なので px はつかないのでは？
```suggestion
				case '0':
```

2024-04-19 19:32 UTC, kurudrive commented
@mtdkei 

padding_left_and_right が 0 : コンテンツ幅になるようにする（ .is-layout-constrained を出力？ ）
padding_left_and_right が 1 : 左右に 4em を付与
padding_left_and_right が 2 : アイテム内の左右余白を 0px に指定

で、 vk_slide_item-paddingLR-none 関連のクラス名の出力処理はここで削除しましょうか。
※ CSSの方は既存ユーザーのためにまだ削除しない

2024-04-24 04:54 UTC, mtdkei commented
@kurudrive 
edit.jsとsave.jsを編集しました。
以下を直したいのですが中々できず悩んでいます。
- 編集画面でコアのパディングを変更しても余白が動かない。
- vk_slider_item-paddingLR-use が vk_slider_item-paddingLR-zero が引き続き出力されてしまう。
- paddingLeftやpaddingRightを switch (padding_left_and_right) で設定しているとこの設定が最優先で聞いてしまう。

2024-06-26 02:50 UTC, mtdkei commented
続きは以下で行うためclose
https://github.com/vektor-inc/vk-blocks-pro/pull/2075

2024-06-26 02:50 UTC, closed without merging