fix：バグ修正 バリエーションにタグが出ていたのを削除
vektor-inc/vk-blocks-pro pull request #2322
Opened 2024-11-14 09:59 UTC by akito-38

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://github.com/vektor-inc/vk-blocks-pro/issues/2313

## どういう変更をしたか？
バリエーションで、カテゴリーバッジ / タグ ブロックが作られていたので、作られないように変更

### スクリーンショットまたは動画

#### 変更前 Before
![image](https://github.com/user-attachments/assets/e6a81f6b-2aa3-49ab-9b92-f07cf224f92c)

#### 変更後 After
![image](https://github.com/user-attachments/assets/7140427c-1db2-4326-9766-738d0677381b)

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど
カテゴリーバッジ / タグ ブロックが表示されてないことを確認。
カテゴリーバッジ及び、カテゴリーバッジ / カテゴリーブロッグを配置して問題無く表示されるか確認。

*
*
*

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

実装者と同じ

*
*
*

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2024-11-14 10:01 UTC, akito-38 commented
すみません。
lint通したら全部変更したようになってますが、実際の変更内容は96行目を追加しただけです。

2024-11-19 06:45 UTC, mtdkei approved these changes
ありがとうございます。確認いたしました。
2人目の確認をお願いいたします。
@mthaichi 
https://github.com/vektor-inc/vk-blocks-pro/issues/2313#issuecomment-2472359155 の見解から、カテゴリーバッジブロックにタグが出ているのが仕様と異なる気がしたのですが、こちらは合っているか念のためご確認いただけたらと思います。

2024-11-25 05:58 UTC, MasayaMORIMOTO commented
@akito-38 
動作には関係ないのですが、下記の記述が他の記述と異なっているのが気になりました。
（コーディング規約の問題です）
修正をお願いできればと思います。
`if(!$taxonomy->hierarchical) continue;`

2024-11-25 09:44 UTC, mthaichi commented
> ありがとうございます。確認いたしました。 2人目の確認をお願いいたします。 @mthaichi [#2313 (comment)](https://github.com/vektor-inc/vk-blocks-pro/issues/2313#issuecomment-2472359155) の見解から、カテゴリーバッジブロックにタグが出ているのが仕様と異なる気がしたのですが、こちらは合っているか念のためご確認いただけたらと思います。

@mtdkei 「カテゴリーバッジ / タグ」ブロックは出ないのが仕様ですので、今回の修正は適切だと思います。

2024-11-25 09:58 UTC, mthaichi commented
> @akito-38 動作には関係ないのですが、下記の記述が他の記述と異なっているのが気になりました。 （コーディング規約の問題です） 修正をお願いできればと思います。 src/blocks/_pro/post-category-badge/index.php の Line: 96 です。 `if(!$taxonomy->hierarchical) continue;`

@akito-38 WordPressのコーディング規約に則ってください。則ってないと composer phpcs でエラーが出て、どこが違うのか確認できます。

・・・あれ？プッシュする時に composer phpcsが走ってエラーになるはずですが、でなかったです？

2024-11-26 06:17 UTC, akito-38 commented
@mthaichi 

ご指摘ありがとうございます。
こちら対応しておきました。

 composer phpcsを実行してみると改行コードについてのエラーも出ていて、
 それを修正したらまた全てが変更箇所になってしましました。

 実際に変えたのは95～97行目です。
 確認お願いいたします。

2024-12-02 02:27 UTC, kurudrive requested changes

2024-12-02 02:27 UTC, kurudrive commented on src/blocks/_pro/post-category-badge/index.php
> +		if ( ! $taxonomy->hierarchical ) {
@akito-38 今回非表示にしたいのは "タグ" なので、"階層無し"  を非表示にするのではなく "post_tag" を除外でよろしくお願いいたします。

2024-12-03 09:09 UTC, akito-38 commented
@kurudrive 
ありがとうございます。
こちら"post_tag"を除外する判定も追加しておきました。
確認お願いします。

2024-12-03 18:38 UTC, kurudrive requested changes

2024-12-03 18:38 UTC, kurudrive commented on src/blocks/_pro/post-category-badge/index.php
> +		if ( ! $taxonomy->hierarchical && 'post_tag' === $taxonomy->name ) {
@akito-38 今回の変更って post_tag を除外するだけなので↓だけでよくないですか（・ｗ・？ 

```suggestion
		if ( 'post_tag' === $taxonomy->name ) {
```

2024-12-04 08:51 UTC, merged