TT4やTT5 テーマで投稿リスト,投稿リストスライダーの見出しの上に余白が開く現象の修正
vektor-inc/vk-blocks-pro pull request #2356
Opened 2024-11-28 07:19 UTC by akito-38

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://github.com/vektor-inc/vk-blocks-pro/issues/2344

## どういう変更をしたか？
TT4やTT5 テーマで表示タイプが「テキスト1カラム」以外のタイプですと、見出しの上に余白が空くので、それを修正しました。
また、見出しの親(黒い半透明のボックス)の高さもずれていたので修正しました。

### スクリーンショットまたは動画

#### 変更前 Before
![image](https://github.com/user-attachments/assets/f26ba36c-9908-4c76-88ee-9f7d5f5af65a)

#### 変更後 After
![image](https://github.com/user-attachments/assets/eede760e-0c17-4d7b-9d9b-562e4959abd7)

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？→cssの修正なのでスキップ

## 変更内容について何を確認したか、どういう方法で確認をしたかなど
投稿リストブロック及び,投稿リストスライダーブロックを配置します。
テーマをTT4にして、タイトル部分の表示が問題無いことを確認しました。
また、タイプを変更してそれぞれ確認しました。
テーマをTT4と念のため、lightningにも変更して同様の確認をしました。

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

・実装者と同じ手順で確認をお願いします。

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2024-11-28 08:57 UTC, goutetsuguma commented
@kurudrive @akito-38 

調整ありがとうございます！修正ファイルを見ていたのですが、修正していただいたscssのファイルで石川さんに質問があります🙇

vk-components / package / の中のファイルは　[vektor-wp-libraries](https://github.com/vektor-inc/vektor-wp-libraries) で修正するのが正しいのでしょうか。

> /*
> このファイルの元ファイルは
> https://github.com/vektor-inc/vektor-wp-libraries
> にあります。修正の際は上記リポジトリのデータを修正してください。
> */

vk-components / package / 内のscssファイルのコメントアウトを見て質問させていただきました

2024-11-28 15:07 UTC, kurudrive requested changes

2024-11-28 15:07 UTC, kurudrive commented on inc/vk-components/package/_scss/_vk-post.scss
> +		font-size: 14px;
@goutetsuguma 
これ 1rem とか 0.88rem だと TT5 とかでまずい？
流体タイポグラフィが主流になりつつあるのでpx指定はなるべく避けたいなと。

2024-11-28 15:08 UTC, kurudrive commented
@goutetsuguma そうですね
vektor-wp-libraries を変更してくださいー。

2024-11-29 14:40 UTC, kurudrive requested changes

2024-11-29 14:40 UTC, kurudrive commented on inc/vk-components/package/_scss/_vk-post.scss
> +		font-size: 14px;
```suggestion
		font-size: 1rem;
```

2024-11-29 15:15 UTC, kurudrive approved these changes

2024-11-29 15:16 UTC, kurudrive commented
https://github.com/vektor-inc/vektor-wp-libraries/pull/146/files

2024-11-29 15:19 UTC, kurudrive commented
@akito-38 とりあえず px 指定はテーマによって流体タイポグラフィが使われているとよろしくないので 1rem 指定に変更いたしました。見た限りこれで問題ないと思います。
@akito-38 @goutetsuguma 軽く見ていただいて問題なければこれでマージしちゃっていただければー！

2024-12-01 22:57 UTC, akito-38 commented
@kurudrive 

こちら確認しました。
1remだと16pxなので若干上にずれてますが、気にならない程度だと思います。
ご調整いただきありがとうございます。

@goutetsuguma 
確認お願いいたします。

2024-12-02 00:58 UTC, goutetsuguma approved these changes

2024-12-02 01:54 UTC, merged