【確認待ち】[ 投稿リスト ] 表示条件 > 投稿タイプ に何もチェックがない場合に「該当の投稿はありません。」が出ない。
vektor-inc/vk-blocks-pro pull request #2357
Opened 2024-11-30 04:06 UTC by MasayaMORIMOTO

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://github.com/vektor-inc/vk-blocks-pro/issues/2346

## どういう変更をしたか？

[ 投稿リスト ] の「表示条件 > 投稿タイプ」 に何もチェックがない場合に
「該当の投稿はありません。」が出るように修正しました。

### スクリーンショットまたは動画

#### 変更後 After

<img width="992" alt="スクリーンショット 2024-11-30 13 01 41" src="https://github.com/user-attachments/assets/b02c46d7-5be2-4005-8137-dc87a31b56fe">

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [x] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [x] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？ → master では確認できない事象だったため、スキップ
- [x] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？ → スキップ

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

* 事前に、投稿と固定ページをいくつか作成しておきます。
* 編集画面で、投稿リストを配置します。
* 投稿リストの右メニュー「表示条件 > 投稿タイプ」で何もチェックしない状態にします。
* 「該当の投稿はありません。」が表示されることを確認します。

## レビュワーに回す前の確認事項

- [x] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

* 事前に、投稿と固定ページをいくつか作成しておきます。
* 編集画面で、投稿リストを配置します。
* 投稿リストの右メニュー「表示条件 > 投稿タイプ」で何もチェックしない状態にします。
* 「該当の投稿はありません。」が表示されることを確認します。

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2024-12-02 00:56 UTC, mtdkei requested changes
@MasayaMORIMOTO 
作業していただき、ありがとうございます。投稿リストでは「該当の投稿はありません。」が表示されるよう修正されていること、確認しました。

ただ、こちらのissueで説明が不足しており、投稿リストスライダーも確認対象となります。申し訳ございません。

上記を前提とし、2点気になることがございました。

## 投稿リストスライダーについて
投稿リストスライダーでは「該当の投稿はありません。」が表示されない挙動を確認しました。「ブロックを空白としてレンダリングします。」と表示されます。
![スクリーンショット 2024-12-02 9 49 58](https://github.com/user-attachments/assets/aaac194e-d740-4b42-875a-f753738bf90a)
masterでも「該当の投稿はありません。」が表示されません。

修正部分のHistoryを確認したところ、 一つ前の https://github.com/vektor-inc/vk-blocks-pro/commit/4e706c41567b23b8e5a0cbd7b3361b0f4e4298ce で「ブロックを空白としてレンダリングします。」を出ないようにするためにこのような調整されている可能性があります。
おそらくその影響で投稿リストでも「該当の投稿はありません。」が表示されなくなったものと思われます。

この挙動が現在の仕様として正しいのか、あるいは投稿リストスライダーにも「該当の投稿はありません。」を表示できるようになるものなのか、@drill-lanser さんの方でも確認をお願いできたらと思います。

## Masterブランチについて
先ほどmasterブランチやサーバー上でもissueと同様の現象を確認しました。どうやら現在はissueの状況が配信されているようです。
お手数ですが、念のため、最新の master ブランチに更新した状態で現象をご確認ください。

長々とすみません。よろしくお願いいたします。

2024-12-02 01:34 UTC, mtdkei commented
@MasayaMORIMOTO 
作業していただき、ありがとうございます。投稿リストでは「該当の投稿はありません。」が表示されるよう修正されていること、確認しました。

ただ、こちらのissueで説明が不足しており、投稿リストスライダーも確認対象となります。申し訳ございません。

上記を前提とし、2点気になることがございました。

## 投稿リストスライダーについて
投稿リストスライダーでは「該当の投稿はありません。」が表示されない挙動を確認しました。「ブロックを空白としてレンダリングします。」と表示されます。
![スクリーンショット 2024-12-02 9 49 58](https://github.com/user-attachments/assets/aaac194e-d740-4b42-875a-f753738bf90a)
masterでも「該当の投稿はありません。」が表示されません。

修正部分のHistoryを確認したところ、 一つ前の https://github.com/vektor-inc/vk-blocks-pro/commit/4e706c41567b23b8e5a0cbd7b3361b0f4e4298ce で「ブロックを空白としてレンダリングします。」を出ないようにするためにこのような調整されている可能性があります。
おそらくその影響で投稿リストでも「該当の投稿はありません。」が表示されなくなったものと思われます。

この挙動が現在の仕様として正しいのか、あるいは投稿リストスライダーにも「該当の投稿はありません。」を表示できるようになるものなのか、@drill-lanser さんの方でも確認をお願いできたらと思います。

## Masterブランチについて
先ほどmasterブランチやサーバー上でもissueと同様の現象を確認しました。
お手数ですが、念のため、最新の master ブランチに更新した状態で現象をご確認ください。

長々とすみません。よろしくお願いいたします。

2024-12-02 01:52 UTC, kurudrive commented
@drill-lancer ↑ 確認よろしくお願いいたします。

2024-12-11 04:31 UTC, drill-lancer commented
確認し、修正しました。

2024-12-12 02:17 UTC, mtdkei approved these changes
投稿リスト、投稿リストスライダーで表示条件 > 投稿タイプ に何もチェックがない場合に「該当の投稿はありません。」が出るようになりました。マージします。

2024-12-12 02:35 UTC, merged