【確認待ち】投稿リストブロック・投稿リストスライダーブロックの「常に最初の投稿から表示する」が効かない不具合を修正
vektor-inc/vk-blocks-pro pull request #2365
Opened 2024-12-10 10:32 UTC by mthaichi

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
#2347 

## どういう変更をしたか？
- WP_Queryに常時offset値が渡ってしまっているので、2ページ目以降表示の場合は、offset値を渡さないように処理を変更

### スクリーンショットまたは動画
画面変更なし

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？
→投稿リスト関連のテストは全面的に書き直す必要を感じるため、#2343 がマージされた後に書き直します。

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

* レビュワー確認方法に同じ

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

* developブランチで当該不具合を確認したあとに、本ブランチに切り替え、問題が修正されていることを確認。
（ウィジェットでフッターに投稿リストブロックを配置し、ブログに10件以上記事を投稿し、アーカイブページでページを切り替えて確認しました）
* 投稿リスト・投稿リストスライダー両ブロックで改善されていることを確認

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2024-12-11 03:03 UTC, sysbird approved these changes

2024-12-11 03:04 UTC, sysbird commented
@mthaichi 
投稿リストブロック・投稿リストスライダーブロックについて、常に最初の投稿から表示する」ON/OFF が動作するのを確認しました
対応ありがとうございます！

2人目どなたか確認お願いします

2024-12-12 02:04 UTC, mtdkei requested changes
ありがとうございます。「常に最初の投稿から表示する」が効くことを確認しました。

すみませんが、一つ気になることがあるので確認させてください。

例えば「常に最初の投稿から表示する」のチェックをせず「オフセット数」を0以外にした時、ウィジェットの編集画面の表示上では「オフセット数」が効いています。
![image](https://github.com/user-attachments/assets/cc785695-ad40-42b5-ae06-8e2ad4358a23)

ただ、フロントエンドでは「オフセット数」が0の状態になります。
![image](https://github.com/user-attachments/assets/8617c0a5-e62c-404e-a495-bac464daea74)
![image](https://github.com/user-attachments/assets/9fd55863-d834-4892-9a7d-d7ac8d44e79d)

本プルリクの説明を見ていると、これは仕様かもしれないと思ったのですがどうでしょうか？

2024-12-12 14:15 UTC, mthaichi commented
@mtdkei なるほどー、元々の仕様がよくわからないですし、元々きちんとこの辺の挙動がちゃんとしていたかわかりませんね。

## 「常に最初の投稿から表示する」がONでオフセット値が指定された場合
- オフセットが指定された場合は、指定されたオフセット数から表示する
## 「常に最初の投稿から表示する」がOFFの場合でオフセット値が指定された場合
- オフセット値分ずらして表示。（オフセット値に3が指定され、1ページあたり6件の表示数ならば、1ページ目はオフセット3、2ページ目は9、3ページ目は15・・・となる）

編集画面は、ページ数が指定されないので、指定されたオフセット値の記事が常に１番目に来ます。

以上のような仕様にしてみましたが、いかがでしょうか。

@kurudrive @drill-lancer このあたり、元々の仕様について記憶ございます？

2024-12-13 01:03 UTC, mtdkei approved these changes
@mthaichi 
ありがとうございます！「常に最初の投稿から表示する」がOFFの場合でオフセット値が指定された場合の動きを確認できました。
こちら承認にしますが、仕様確認待ちのためマージまだ行わないことにします。

2024-12-23 01:43 UTC, drill-lancer commented
私は記憶にございませんので撤退いたします。

2024-12-23 02:44 UTC, kurudrive commented on readme.txt
> +[ Bug fix ][ Post List ( Pro ) ] Fix the issue where posts are always displayed from the first post regardless of the "Display from the first post always" setting.
```suggestion
[ Bug fix ][ Post List ( Pro ) / Post List Slider ( Pro ) ] Fix the issue where posts are always displayed from the first post regardless of the "Display from the first post always" setting.
```

@mthaichi 同じ内容の変更を複数のブロックに実施した場合は / 区切りで一つの項目で記入いただければいいかなと思いまするー。

2024-12-23 03:56 UTC, merged